import Navbar from '@/components/layout/navbar'
import './globals.scss'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/core/utils'
import { Viewport, Metadata } from 'next'
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers';
// import { VercelToolbar } from '@vercel/toolbar/next';
import Footer from '@/components/layout/footer'
import NextNProgressClient from './progress'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export const viewport: Viewport = {
	themeColor: '#3d2d37',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn(inter.className)}>
				<NextNProgressClient />
				<Providers>
					<div className="bg-home-gradient font-poppins min-h-100vh bg-50 bg-cover bg-no-repeat">
						<Navbar />
						{children}
						{/* <Suspense>
							<VercelToolbar />
						</Suspense> */}
						<Footer />
					</div>
				</Providers>
			</body>
		</html>
	)
}
