/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokensGet200Response {
    /// The requested tokens
    #[serde(rename = "1", skip_serializing_if = "Option::is_none")]
    pub param_1: Option<Vec<crate::models::Token>>,
}

impl TokensGet200Response {
    pub fn new() -> TokensGet200Response {
        TokensGet200Response {
            param_1: None,
        }
    }
}


