/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Action : Object describing what happens in a `Step`



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// The id of the chain where the transfer should start
    #[serde(rename = "fromChainId")]
    pub from_chain_id: f32,
    /// The amount that should be transferred including all decimals
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    #[serde(rename = "fromToken")]
    pub from_token: Box<crate::models::Token>,
    /// The id of the chain where the transfer should end
    #[serde(rename = "toChainId")]
    pub to_chain_id: f32,
    #[serde(rename = "toToken")]
    pub to_token: Box<crate::models::Token>,
    /// The maximum allowed slippage
    #[serde(rename = "slippage", skip_serializing_if = "Option::is_none")]
    pub slippage: Option<f64>,
    /// The sending wallet address
    #[serde(rename = "fromAddress", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,
    /// The receiving wallet address
    #[serde(rename = "toAddress", skip_serializing_if = "Option::is_none")]
    pub to_address: Option<String>,
}

impl Action {
    /// Object describing what happens in a `Step`
    pub fn new(from_chain_id: f32, from_amount: String, from_token: crate::models::Token, to_chain_id: f32, to_token: crate::models::Token) -> Action {
        Action {
            from_chain_id,
            from_amount,
            from_token: Box::new(from_token),
            to_chain_id,
            to_token: Box::new(to_token),
            slippage: None,
            from_address: None,
            to_address: None,
        }
    }
}


