/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AllowDenyPrefer : Object defining which tools should be allowed, denied and preferred



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllowDenyPrefer {
    /// Allowed tools
    #[serde(rename = "allow", skip_serializing_if = "Option::is_none")]
    pub allow: Option<Vec<String>>,
    /// Forbidden tools
    #[serde(rename = "deny", skip_serializing_if = "Option::is_none")]
    pub deny: Option<Vec<String>>,
    /// Preferred tools
    #[serde(rename = "prefer", skip_serializing_if = "Option::is_none")]
    pub prefer: Option<Vec<String>>,
}

impl AllowDenyPrefer {
    /// Object defining which tools should be allowed, denied and preferred
    pub fn new() -> AllowDenyPrefer {
        AllowDenyPrefer {
            allow: None,
            deny: None,
            prefer: None,
        }
    }
}


