/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BasicTransaction : A basic transaction object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicTransaction {
    /// The hash of the transaction
    #[serde(rename = "txHash")]
    pub tx_hash: String,
    /// Link to a block explorer showing the transaction
    #[serde(rename = "txLink")]
    pub tx_link: String,
    /// The amount of the transaction
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
    /// The id of the chain
    #[serde(rename = "chainId")]
    pub chain_id: f32,
}

impl BasicTransaction {
    /// A basic transaction object
    pub fn new(tx_hash: String, tx_link: String, amount: String, token: crate::models::Token, chain_id: f32) -> BasicTransaction {
        BasicTransaction {
            tx_hash,
            tx_link,
            amount,
            token: Box::new(token),
            chain_id,
        }
    }
}


