/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BridgesEnum {
    #[serde(rename = "hop")]
    Hop,
    #[serde(rename = "multichain")]
    Multichain,
    #[serde(rename = "cbridge")]
    Cbridge,
    #[serde(rename = "celercircle")]
    Celercircle,
    #[serde(rename = "connext")]
    Connext,
    #[serde(rename = "hyphen")]
    Hyphen,
    #[serde(rename = "optimism")]
    Optimism,
    #[serde(rename = "polygon")]
    Polygon,
    #[serde(rename = "arbitrum")]
    Arbitrum,
    #[serde(rename = "avalanche")]
    Avalanche,
    #[serde(rename = "across")]
    Across,
    #[serde(rename = "stargate")]
    Stargate,
    #[serde(rename = "gnosis")]
    Gnosis,
    #[serde(rename = "omni")]
    Omni,
    #[serde(rename = "amarok")]
    Amarok,
    #[serde(rename = "lifuel")]
    Lifuel,
    #[serde(rename = "celerim")]
    Celerim,

}

impl ToString for BridgesEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Hop => String::from("hop"),
            Self::Multichain => String::from("multichain"),
            Self::Cbridge => String::from("cbridge"),
            Self::Celercircle => String::from("celercircle"),
            Self::Connext => String::from("connext"),
            Self::Hyphen => String::from("hyphen"),
            Self::Optimism => String::from("optimism"),
            Self::Polygon => String::from("polygon"),
            Self::Arbitrum => String::from("arbitrum"),
            Self::Avalanche => String::from("avalanche"),
            Self::Across => String::from("across"),
            Self::Stargate => String::from("stargate"),
            Self::Gnosis => String::from("gnosis"),
            Self::Omni => String::from("omni"),
            Self::Amarok => String::from("amarok"),
            Self::Lifuel => String::from("lifuel"),
            Self::Celerim => String::from("celerim"),
        }
    }
}

impl Default for BridgesEnum {
    fn default() -> BridgesEnum {
        Self::Hop
    }
}




