/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bridge {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<crate::models::BridgesEnum>,
    /// The common name of the tool
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The logo of the tool
    #[serde(rename = "logoURI", skip_serializing_if = "Option::is_none")]
    pub logo_uri: Option<String>,
    #[serde(rename = "supportedChains", skip_serializing_if = "Option::is_none")]
    pub supported_chains: Option<Vec<crate::models::SupportedChains>>,
}

impl Bridge {
    pub fn new() -> Bridge {
        Bridge {
            key: None,
            name: None,
            logo_uri: None,
            supported_chains: None,
        }
    }
}


