/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BridgeDefinition : The defintion of a bridge with the transferrable token pair



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeDefinition {
    #[serde(rename = "tool")]
    pub tool: crate::models::BridgesEnum,
    /// From which chain transfers can happen
    #[serde(rename = "fromChainId")]
    pub from_chain_id: f32,
    #[serde(rename = "fromToken")]
    pub from_token: Box<crate::models::Token>,
    /// To which chain transfers can happen
    #[serde(rename = "toChainId")]
    pub to_chain_id: f32,
    #[serde(rename = "toToken")]
    pub to_token: Box<crate::models::Token>,
    /// The maximum amount that can be sent in one transfer
    #[serde(rename = "maximumTransfer")]
    pub maximum_transfer: String,
    /// The minimum amount that can be sent in one transfer
    #[serde(rename = "minimumTransfer")]
    pub minimum_transfer: String,
    /// The rate taken for swap fees
    #[serde(rename = "swapFeeRate")]
    pub swap_fee_rate: String,
    /// The minimum swap fees that will be taken
    #[serde(rename = "swapFeeMinimum")]
    pub swap_fee_minimum: String,
    /// The maximum swap fees that might occur
    #[serde(rename = "swapFeeMaximum")]
    pub swap_fee_maximum: String,
}

impl BridgeDefinition {
    /// The defintion of a bridge with the transferrable token pair
    pub fn new(tool: crate::models::BridgesEnum, from_chain_id: f32, from_token: crate::models::Token, to_chain_id: f32, to_token: crate::models::Token, maximum_transfer: String, minimum_transfer: String, swap_fee_rate: String, swap_fee_minimum: String, swap_fee_maximum: String) -> BridgeDefinition {
        BridgeDefinition {
            tool,
            from_chain_id,
            from_token: Box::new(from_token),
            to_chain_id,
            to_token: Box::new(to_token),
            maximum_transfer,
            minimum_transfer,
            swap_fee_rate,
            swap_fee_minimum,
            swap_fee_maximum,
        }
    }
}


