/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChainMetamask : Information about the chain from metamask. Contains data about RPCs and block explorers



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainMetamask {
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<String>,
    #[serde(rename = "blockExplorerUrls", skip_serializing_if = "Option::is_none")]
    pub block_explorer_urls: Option<Vec<String>>,
    #[serde(rename = "chainName", skip_serializing_if = "Option::is_none")]
    pub chain_name: Option<String>,
    #[serde(rename = "nativeCurrency", skip_serializing_if = "Option::is_none")]
    pub native_currency: Option<Box<crate::models::ChainMetamaskNativeCurrency>>,
    #[serde(rename = "rpcUrls", skip_serializing_if = "Option::is_none")]
    pub rpc_urls: Option<Vec<String>>,
}

impl ChainMetamask {
    /// Information about the chain from metamask. Contains data about RPCs and block explorers
    pub fn new() -> ChainMetamask {
        ChainMetamask {
            chain_id: None,
            block_explorer_urls: None,
            chain_name: None,
            native_currency: None,
            rpc_urls: None,
        }
    }
}


