/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Chain : Representation of a chain



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Chain {
    /// Short string represenation of the chain
    #[serde(rename = "key")]
    pub key: String,
    /// Type of the chain
    #[serde(rename = "chainType", skip_serializing_if = "Option::is_none")]
    pub chain_type: Option<String>,
    /// Name of the chain
    #[serde(rename = "name")]
    pub name: String,
    /// The native coin of the chain
    #[serde(rename = "coin")]
    pub coin: String,
    /// Unique id of the chain
    #[serde(rename = "id")]
    pub id: f32,
    /// Whether the chain is mainnet or not
    #[serde(rename = "mainnet")]
    pub mainnet: bool,
    /// Logo of the chain
    #[serde(rename = "logoURI", skip_serializing_if = "Option::is_none")]
    pub logo_uri: Option<String>,
    /// Url to the list of available tokens
    #[serde(rename = "tokenlistUrl", skip_serializing_if = "Option::is_none")]
    pub tokenlist_url: Option<String>,
    /// List of available faucets
    #[serde(rename = "faucetUrls", skip_serializing_if = "Option::is_none")]
    pub faucet_urls: Option<Vec<String>>,
    /// The multicall contract address
    #[serde(rename = "multicallAddress", skip_serializing_if = "Option::is_none")]
    pub multicall_address: Option<String>,
    #[serde(rename = "metamask", skip_serializing_if = "Option::is_none")]
    pub metamask: Option<Box<crate::models::ChainMetamask>>,
    #[serde(rename = "nativeToken", skip_serializing_if = "Option::is_none")]
    pub native_token: Option<crate::models::Token>,
}

impl Chain {
    /// Representation of a chain
    pub fn new(key: String, name: String, coin: String, id: f32, mainnet: bool) -> Chain {
        Chain {
            key,
            chain_type: None,
            name,
            coin,
            id,
            mainnet,
            logo_uri: None,
            tokenlist_url: None,
            faucet_urls: None,
            multicall_address: None,
            metamask: None,
            native_token: None,
        }
    }
}


