/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChainsResponse : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainsResponse {
    #[serde(rename = "chains", skip_serializing_if = "Option::is_none")]
    pub chains: Option<Vec<crate::models::Chain>>,
}

impl ChainsResponse {
    /// 
    pub fn new() -> ChainsResponse {
        ChainsResponse {
            chains: None,
        }
    }
}


