/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainMetamaskNativeCurrency {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "decimals", skip_serializing_if = "Option::is_none")]
    pub decimals: Option<f32>,
}

impl ChainMetamaskNativeCurrency {
    pub fn new() -> ChainMetamaskNativeCurrency {
        ChainMetamaskNativeCurrency {
            name: None,
            symbol: None,
            decimals: None,
        }
    }
}


