/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Connection : A connection from one chain to another defined by tokens that can be exchanged for another.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Connection {
    /// The sending chain
    #[serde(rename = "fromChainId")]
    pub from_chain_id: f32,
    /// The receiving chain
    #[serde(rename = "toChainId")]
    pub to_chain_id: f32,
    /// List of possible tokens that can be sent
    #[serde(rename = "fromTokens")]
    pub from_tokens: Vec<crate::models::Token>,
    /// List of tokens that can be sent
    #[serde(rename = "toTokens")]
    pub to_tokens: Vec<crate::models::Token>,
}

impl Connection {
    /// A connection from one chain to another defined by tokens that can be exchanged for another.
    pub fn new(from_chain_id: f32, to_chain_id: f32, from_tokens: Vec<crate::models::Token>, to_tokens: Vec<crate::models::Token>) -> Connection {
        Connection {
            from_chain_id,
            to_chain_id,
            from_tokens,
            to_tokens,
        }
    }
}


