/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ConnectionsResponse : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionsResponse {
    /// The possible connections
    #[serde(rename = "connections", skip_serializing_if = "Option::is_none")]
    pub connections: Option<Vec<crate::models::Connection>>,
}

impl ConnectionsResponse {
    /// 
    pub fn new() -> ConnectionsResponse {
        ConnectionsResponse {
            connections: None,
        }
    }
}


