/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContractCallsRequest : Object defining instructions on how to perform multiple cross-chain/same-chain calls



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractCallsRequest {
    /// The sending chain. Can be the chain id or chain key
    #[serde(rename = "fromChain")]
    pub from_chain: f32,
    /// The token that should be transferred. Can be the address or the symbol
    #[serde(rename = "fromToken")]
    pub from_token: String,
    /// The wallet that will send the transaction and contains the starting token
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    /// The receiving chain. Can be the chain id or chain key
    #[serde(rename = "toChain")]
    pub to_chain: f32,
    /// The token required to perform the contract interation (can be something to stake, donate or to be used as payment)
    #[serde(rename = "toToken")]
    pub to_token: String,
    /// The amount of token required by the contract interaction. The LI.FI API will try and generate a quote that guarantees at least that amount on the destination chain.
    #[serde(rename = "toAmount")]
    pub to_amount: String,
    #[serde(rename = "contractCalls")]
    pub contract_calls: Vec<crate::models::ContractCall>,
    /// If the call fails, use this address to send the bridged tokens to. If none is specified, the sending address will be used.
    #[serde(rename = "toFallbackAddress", skip_serializing_if = "Option::is_none")]
    pub to_fallback_address: Option<String>,
    /// The maximum allowed slippage for the transaction as a decimal value. 0.005 represents 0.5%.
    #[serde(rename = "slippage", skip_serializing_if = "Option::is_none")]
    pub slippage: Option<f64>,
    /// A string containing tracking information about the integrator of the API
    #[serde(rename = "integrator", skip_serializing_if = "Option::is_none")]
    pub integrator: Option<String>,
    /// A string containing tracking information about the referrer of the integrator
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    /// List of bridges that are allowed for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    #[serde(rename = "allowBridges", skip_serializing_if = "Option::is_none")]
    pub allow_bridges: Option<Vec<String>>,
    /// List of bridges that are not allowed for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    #[serde(rename = "denyBridges", skip_serializing_if = "Option::is_none")]
    pub deny_bridges: Option<Vec<String>>,
    /// List of bridges that should be preferred for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    #[serde(rename = "preferBridges", skip_serializing_if = "Option::is_none")]
    pub prefer_bridges: Option<Vec<String>>,
    /// List of exchanges that are allowed for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    #[serde(rename = "allowExchanges", skip_serializing_if = "Option::is_none")]
    pub allow_exchanges: Option<Vec<String>>,
    /// List of exchanges that are not allowed for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    #[serde(rename = "denyExchanges", skip_serializing_if = "Option::is_none")]
    pub deny_exchanges: Option<Vec<String>>,
    /// List of exchanges that should be preferred for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    #[serde(rename = "preferExchanges", skip_serializing_if = "Option::is_none")]
    pub prefer_exchanges: Option<Vec<String>>,
    /// The price impact threshold above which routes are hidden. As an example, one should specify 0.15 (15%) to hide routes with more than 15% price impact. The default is 10%.
    #[serde(rename = "maxPriceImpact", skip_serializing_if = "Option::is_none")]
    pub max_price_impact: Option<f64>,
    /// Whether swaps or other contract calls should be allowed as part of the destination transaction of a bridge transfer. Separate swap transactions on the destination chain are not affected by this flag. By default, parameter is `true`.
    #[serde(rename = "allowDestinationCall", skip_serializing_if = "Option::is_none")]
    pub allow_destination_call: Option<bool>,
}

impl ContractCallsRequest {
    /// Object defining instructions on how to perform multiple cross-chain/same-chain calls
    pub fn new(from_chain: f32, from_token: String, from_address: String, to_chain: f32, to_token: String, to_amount: String, contract_calls: Vec<crate::models::ContractCall>) -> ContractCallsRequest {
        ContractCallsRequest {
            from_chain,
            from_token,
            from_address,
            to_chain,
            to_token,
            to_amount,
            contract_calls,
            to_fallback_address: None,
            slippage: None,
            integrator: None,
            referrer: None,
            allow_bridges: None,
            deny_bridges: None,
            prefer_bridges: None,
            allow_exchanges: None,
            deny_exchanges: None,
            prefer_exchanges: None,
            max_price_impact: None,
            allow_destination_call: None,
        }
    }
}


