/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContractCall : Object defining a single arbitrary contract call



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractCall {
    /// The amount that will feed into this contract call. This is not dependent on how much was bridged or deposited before - it's the *expected* amount of token available on order to execute the call.
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    /// The token that will feed into this contract call. E.g. a ETH staking transaction would expect to have ETH available.
    #[serde(rename = "fromTokenAddress")]
    pub from_token_address: String,
    /// The address of the contract to interact with.
    #[serde(rename = "toContractAddress")]
    pub to_contract_address: String,
    /// The calldata to be sent to the contract for the interaction on the destination chain.
    #[serde(rename = "toContractCallData")]
    pub to_contract_call_data: String,
    /// The estimated gas used by the destination call. If this value is incorrect, the interaction may fail -- choose this carefully!
    #[serde(rename = "toContractGasLimit")]
    pub to_contract_gas_limit: String,
    /// If the approval address is different thant the contract to call, specify that address here
    #[serde(rename = "toApprovalAddress", skip_serializing_if = "Option::is_none")]
    pub to_approval_address: Option<String>,
    /// If the contract outputs a token, specify its address here. (E.g. staking ETH produces stETH)
    #[serde(rename = "toTokenAddress", skip_serializing_if = "Option::is_none")]
    pub to_token_address: Option<String>,
}

impl ContractCall {
    /// Object defining a single arbitrary contract call
    pub fn new(from_amount: String, from_token_address: String, to_contract_address: String, to_contract_call_data: String, to_contract_gas_limit: String) -> ContractCall {
        ContractCall {
            from_amount,
            from_token_address,
            to_contract_address,
            to_contract_call_data,
            to_contract_gas_limit,
            to_approval_address: None,
            to_token_address: None,
        }
    }
}


