/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Estimate : An estimate for the current transfer



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Estimate {
    /// The amount that should be transferred
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    /// The estimated resulting amount of the `toToken`
    #[serde(rename = "toAmount")]
    pub to_amount: String,
    /// The minimal outcome of the transfer
    #[serde(rename = "toAmountMin")]
    pub to_amount_min: String,
    /// The contract address for the approval
    #[serde(rename = "approvalAddress")]
    pub approval_address: String,
    /// Fees included in the transfer
    #[serde(rename = "feeCosts", skip_serializing_if = "Option::is_none")]
    pub fee_costs: Option<Vec<crate::models::FeeCost>>,
    /// Gas costs included in the transfer
    #[serde(rename = "gasCosts", skip_serializing_if = "Option::is_none")]
    pub gas_costs: Option<Vec<crate::models::GasCost>>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::EstimateData>>,
}

impl Estimate {
    /// An estimate for the current transfer
    pub fn new(from_amount: String, to_amount: String, to_amount_min: String, approval_address: String) -> Estimate {
        Estimate {
            from_amount,
            to_amount,
            to_amount_min,
            approval_address,
            fee_costs: None,
            gas_costs: None,
            data: None,
        }
    }
}


