/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EstimateData : Arbitrary data that depends on the the used tool



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimateData {
    #[serde(rename = "bid", skip_serializing_if = "Option::is_none")]
    pub bid: Option<Box<crate::models::StepRequestEstimateDataBid>>,
    #[serde(rename = "bidSignature", skip_serializing_if = "Option::is_none")]
    pub bid_signature: Option<String>,
    #[serde(rename = "gasFeeInReceivingToken", skip_serializing_if = "Option::is_none")]
    pub gas_fee_in_receiving_token: Option<String>,
    #[serde(rename = "totalFee", skip_serializing_if = "Option::is_none")]
    pub total_fee: Option<String>,
    #[serde(rename = "metaTxRelayerFee", skip_serializing_if = "Option::is_none")]
    pub meta_tx_relayer_fee: Option<String>,
    #[serde(rename = "routerFee", skip_serializing_if = "Option::is_none")]
    pub router_fee: Option<String>,
}

impl EstimateData {
    /// Arbitrary data that depends on the the used tool
    pub fn new() -> EstimateData {
        EstimateData {
            bid: None,
            bid_signature: None,
            gas_fee_in_receiving_token: None,
            total_fee: None,
            meta_tx_relayer_fee: None,
            router_fee: None,
        }
    }
}


