/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExchangesEnum {
    #[serde(rename = "1inch")]
    Variant1inch,
    #[serde(rename = "paraswap")]
    Paraswap,
    #[serde(rename = "openocean")]
    Openocean,
    #[serde(rename = "0x")]
    Variant0x,
    #[serde(rename = "dodo")]
    Dodo,
    #[serde(rename = "uniswap")]
    Uniswap,
    #[serde(rename = "sushiswap")]
    Sushiswap,
    #[serde(rename = "quickswap")]
    Quickswap,
    #[serde(rename = "honeyswap")]
    Honeyswap,
    #[serde(rename = "pancakeswap")]
    Pancakeswap,
    #[serde(rename = "spookyswap")]
    Spookyswap,
    #[serde(rename = "viperswap")]
    Viperswap,
    #[serde(rename = "solarbeam")]
    Solarbeam,
    #[serde(rename = "spiritswap")]
    Spiritswap,

}

impl ToString for ExchangesEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1inch => String::from("1inch"),
            Self::Paraswap => String::from("paraswap"),
            Self::Openocean => String::from("openocean"),
            Self::Variant0x => String::from("0x"),
            Self::Dodo => String::from("dodo"),
            Self::Uniswap => String::from("uniswap"),
            Self::Sushiswap => String::from("sushiswap"),
            Self::Quickswap => String::from("quickswap"),
            Self::Honeyswap => String::from("honeyswap"),
            Self::Pancakeswap => String::from("pancakeswap"),
            Self::Spookyswap => String::from("spookyswap"),
            Self::Viperswap => String::from("viperswap"),
            Self::Solarbeam => String::from("solarbeam"),
            Self::Spiritswap => String::from("spiritswap"),
        }
    }
}

impl Default for ExchangesEnum {
    fn default() -> ExchangesEnum {
        Self::Variant1inch
    }
}




