/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExchangeDefinition : The defintion of an exchange with the avaiable chains



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeDefinition {
    /// The exchange tool
    #[serde(rename = "tool")]
    pub tool: Tool,
    /// The available chains for this tool
    #[serde(rename = "chains")]
    pub chains: Vec<f32>,
}

impl ExchangeDefinition {
    /// The defintion of an exchange with the avaiable chains
    pub fn new(tool: Tool, chains: Vec<f32>) -> ExchangeDefinition {
        ExchangeDefinition {
            tool,
            chains,
        }
    }
}

/// The exchange tool
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tool {
    #[serde(rename = "1inch")]
    Variant1inch,
    #[serde(rename = "paraswap")]
    Paraswap,
    #[serde(rename = "openocean")]
    Openocean,
    #[serde(rename = "0x")]
    Variant0x,
}

impl Default for Tool {
    fn default() -> Tool {
        Self::Variant1inch
    }
}

