/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeBalances {
    /// The id of the chain
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<f32>,
    #[serde(rename = "tokenBalances", skip_serializing_if = "Option::is_none")]
    pub token_balances: Option<Vec<crate::models::TokenBalances>>,
}

impl FeeBalances {
    pub fn new() -> FeeBalances {
        FeeBalances {
            chain_id: None,
            token_balances: None,
        }
    }
}


