/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FeeCost : Fees included in the transfer



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeCost {
    /// Name of the fee
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the fee costs
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Percentage of how much fees are taken
    #[serde(rename = "percentage")]
    pub percentage: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
    /// The amount of fees
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// The amount of fees in USD
    #[serde(rename = "amountUSD")]
    pub amount_usd: String,
    /// Whether fee is included into transfer's `fromAmount`
    #[serde(rename = "included")]
    pub included: bool,
}

impl FeeCost {
    /// Fees included in the transfer
    pub fn new(name: String, percentage: String, token: crate::models::Token, amount_usd: String, included: bool) -> FeeCost {
        FeeCost {
            name,
            description: None,
            percentage,
            token: Box::new(token),
            amount: None,
            amount_usd,
            included,
        }
    }
}


