/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GasPrice {
    #[serde(rename = "standard", skip_serializing_if = "Option::is_none")]
    pub standard: Option<f32>,
    #[serde(rename = "fast", skip_serializing_if = "Option::is_none")]
    pub fast: Option<f32>,
    #[serde(rename = "fastest", skip_serializing_if = "Option::is_none")]
    pub fastest: Option<f32>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<f32>,
}

impl GasPrice {
    pub fn new() -> GasPrice {
        GasPrice {
            standard: None,
            fast: None,
            fastest: None,
            last_updated: None,
        }
    }
}


