/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GasCost : Gas costs included in the transfer



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GasCost {
    /// Can be one of `SUM`, `APPROVE` or `SEND`
    #[serde(rename = "type")]
    pub r#type: String,
    /// Suggested current standard price for the chain
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    /// Estimation how much gas will be needed
    #[serde(rename = "estimate", skip_serializing_if = "Option::is_none")]
    pub estimate: Option<String>,
    /// Suggested gas limit
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// Amount of the gas cost
    #[serde(rename = "amount")]
    pub amount: String,
    /// Amount of the gas cost in USD
    #[serde(rename = "amountUSD", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
}

impl GasCost {
    /// Gas costs included in the transfer
    pub fn new(r#type: String, amount: String, token: crate::models::Token) -> GasCost {
        GasCost {
            r#type,
            price: None,
            estimate: None,
            limit: None,
            amount,
            amount_usd: None,
            token: Box::new(token),
        }
    }
}


