/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntegratorWithdrawalResponseTransactionRequest : The transaction request



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegratorWithdrawalResponseTransactionRequest {
    /// The transaction's data
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// The FeeCollector's contract address for the specified chain
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl IntegratorWithdrawalResponseTransactionRequest {
    /// The transaction request
    pub fn new() -> IntegratorWithdrawalResponseTransactionRequest {
        IntegratorWithdrawalResponseTransactionRequest {
            data: None,
            to: None,
        }
    }
}


