/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntegratorResponse : Integrator's fee balance by chain



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegratorResponse {
    /// The integrator's name or wallet address
    #[serde(rename = "integratorId")]
    pub integrator_id: String,
    /// The fee balances of the integrator
    #[serde(rename = "feeBalances", skip_serializing_if = "Option::is_none")]
    pub fee_balances: Option<Vec<crate::models::FeeBalances>>,
}

impl IntegratorResponse {
    /// Integrator's fee balance by chain
    pub fn new(integrator_id: String) -> IntegratorResponse {
        IntegratorResponse {
            integrator_id,
            fee_balances: None,
        }
    }
}


