/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntegratorWithdrawalResponse : Transaction request for withdrawing integrator's collected fees for the specified chain



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegratorWithdrawalResponse {
    #[serde(rename = "transactionRequest")]
    pub transaction_request: Box<crate::models::IntegratorWithdrawalResponseTransactionRequest>,
}

impl IntegratorWithdrawalResponse {
    /// Transaction request for withdrawing integrator's collected fees for the specified chain
    pub fn new(transaction_request: crate::models::IntegratorWithdrawalResponseTransactionRequest) -> IntegratorWithdrawalResponse {
        IntegratorWithdrawalResponse {
            transaction_request: Box::new(transaction_request),
        }
    }
}


