/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LiFuelStatusStateEnum {
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "DONE")]
    Done,

}

impl ToString for LiFuelStatusStateEnum {
    fn to_string(&self) -> String {
        match self {
            Self::NotFound => String::from("NOT_FOUND"),
            Self::Pending => String::from("PENDING"),
            Self::Done => String::from("DONE"),
        }
    }
}

impl Default for LiFuelStatusStateEnum {
    fn default() -> LiFuelStatusStateEnum {
        Self::NotFound
    }
}




