/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiFuelStatus {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::LiFuelStatusStateEnum>,
    #[serde(rename = "sending", skip_serializing_if = "Option::is_none")]
    pub sending: Option<Box<crate::models::TxInfo>>,
    #[serde(rename = "receiving", skip_serializing_if = "Option::is_none")]
    pub receiving: Option<Box<crate::models::TxInfo>>,
}

impl LiFuelStatus {
    pub fn new() -> LiFuelStatus {
        LiFuelStatus {
            status: None,
            sending: None,
            receiving: None,
        }
    }
}


