/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PossiblitiesRequest : Object defining preferences regarding chain, exchanges and bridges



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PossiblitiesRequest {
    /// The ids of the chains that should be taken into consideration for the possibilities
    #[serde(rename = "chains", skip_serializing_if = "Option::is_none")]
    pub chains: Option<Vec<f32>>,
    #[serde(rename = "bridges", skip_serializing_if = "Option::is_none")]
    pub bridges: Option<Box<crate::models::AllowDenyPrefer>>,
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Box<crate::models::AllowDenyPrefer>>,
    /// To reduce the size of the returned possibilities, you can select which kind of information you like to see. Possible values are `chains`, `tokens`, `bridges`, and `exchanges`.
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<crate::models::PossibilitiesTopicEnum>>,
}

impl PossiblitiesRequest {
    /// Object defining preferences regarding chain, exchanges and bridges
    pub fn new() -> PossiblitiesRequest {
        PossiblitiesRequest {
            chains: None,
            bridges: None,
            exchanges: None,
            include: None,
        }
    }
}


