/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PossibilitiesTopicEnum {
    #[serde(rename = "chains")]
    Chains,
    #[serde(rename = "tokens")]
    Tokens,
    #[serde(rename = "bridges")]
    Bridges,
    #[serde(rename = "exchanges")]
    Exchanges,

}

impl ToString for PossibilitiesTopicEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Chains => String::from("chains"),
            Self::Tokens => String::from("tokens"),
            Self::Bridges => String::from("bridges"),
            Self::Exchanges => String::from("exchanges"),
        }
    }
}

impl Default for PossibilitiesTopicEnum {
    fn default() -> PossibilitiesTopicEnum {
        Self::Chains
    }
}




