/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PossibilitiesResponse : Object listing current possibilities for any-to-any cross-chain-swaps based on the provided preferences



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PossibilitiesResponse {
    /// Possible chains that can be sent from or to
    #[serde(rename = "chains")]
    pub chains: Vec<crate::models::Chain>,
    /// Possible `Tokens` that can be transferred
    #[serde(rename = "tokens")]
    pub tokens: Vec<crate::models::Token>,
    /// Possible exchanges that can be used for transfers
    #[serde(rename = "exchanges")]
    pub exchanges: Vec<crate::models::ExchangeDefinition>,
    /// Possible bridges that can be used for transfers
    #[serde(rename = "bridges")]
    pub bridges: Vec<crate::models::BridgeDefinition>,
}

impl PossibilitiesResponse {
    /// Object listing current possibilities for any-to-any cross-chain-swaps based on the provided preferences
    pub fn new(chains: Vec<crate::models::Chain>, tokens: Vec<crate::models::Token>, exchanges: Vec<crate::models::ExchangeDefinition>, bridges: Vec<crate::models::BridgeDefinition>) -> PossibilitiesResponse {
        PossibilitiesResponse {
            chains,
            tokens,
            exchanges,
            bridges,
        }
    }
}


