/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoutesRequest : A description of a token transfer



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutesRequest {
    /// The sending chain id
    #[serde(rename = "fromChainId")]
    pub from_chain_id: f32,
    /// The amount that should be transferred including all decimals (e.g. 1000000 for 1 USDC (6 decimals))
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    /// The address of the sending `Token`
    #[serde(rename = "fromTokenAddress")]
    pub from_token_address: String,
    /// The id of the receiving chain
    #[serde(rename = "toChainId")]
    pub to_chain_id: f32,
    /// The address of the receiving `Token`
    #[serde(rename = "toTokenAddress")]
    pub to_token_address: String,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::RouteOptions>>,
    /// The sending wallet address
    #[serde(rename = "fromAddress", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,
    /// The receicing wallet address
    #[serde(rename = "toAddress", skip_serializing_if = "Option::is_none")]
    pub to_address: Option<String>,
}

impl RoutesRequest {
    /// A description of a token transfer
    pub fn new(from_chain_id: f32, from_amount: String, from_token_address: String, to_chain_id: f32, to_token_address: String) -> RoutesRequest {
        RoutesRequest {
            from_chain_id,
            from_amount,
            from_token_address,
            to_chain_id,
            to_token_address,
            options: None,
            from_address: None,
            to_address: None,
        }
    }
}


