/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoutesResponse : A list of routes that can be used to realize the described transfer of tokens



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutesResponse {
    /// List of possible `Routes` for the given transfer
    #[serde(rename = "routes")]
    pub routes: Vec<crate::models::Route>,
    /// An object representing the routes that are unavailable for the given transfer
    #[serde(rename = "unavailableRoutes", skip_serializing_if = "Option::is_none")]
    pub unavailable_routes: Option<Vec<crate::models::UnavailableRoutes>>,
}

impl RoutesResponse {
    /// A list of routes that can be used to realize the described transfer of tokens
    pub fn new(routes: Vec<crate::models::Route>) -> RoutesResponse {
        RoutesResponse {
            routes,
            unavailable_routes: None,
        }
    }
}


