/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RouteOptions : Optional settings for the route



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteOptions {
    /// Custom string the developer who integrates LiFi can set
    #[serde(rename = "integrator", skip_serializing_if = "Option::is_none")]
    pub integrator: Option<String>,
    /// The maximum allowed slippage
    #[serde(rename = "slippage", skip_serializing_if = "Option::is_none")]
    pub slippage: Option<f64>,
    #[serde(rename = "bridges", skip_serializing_if = "Option::is_none")]
    pub bridges: Option<Box<crate::models::AllowDenyPrefer>>,
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Box<crate::models::AllowDenyPrefer>>,
    /// The way the resulting routes should be ordered
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<Order>,
    /// Whether chain switches should be allowed in the routes
    #[serde(rename = "allowSwitchChain", skip_serializing_if = "Option::is_none")]
    pub allow_switch_chain: Option<bool>,
    /// Integrators can set a wallet address as referrer to track them
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    /// The percent of the integrator's fee that is taken from every transaction
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<f64>,
    /// The price impact threshold above which routes are hidden. As an example, one should specify 0.15 (15%) to hide routes with more than 15% price impact. The default is 10%.
    #[serde(rename = "maxPriceImpact", skip_serializing_if = "Option::is_none")]
    pub max_price_impact: Option<f64>,
}

impl RouteOptions {
    /// Optional settings for the route
    pub fn new() -> RouteOptions {
        RouteOptions {
            integrator: None,
            slippage: None,
            bridges: None,
            exchanges: None,
            order: None,
            allow_switch_chain: None,
            referrer: None,
            fee: None,
            max_price_impact: None,
        }
    }
}

/// The way the resulting routes should be ordered
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Order {
    #[serde(rename = "RECOMMENDED")]
    Recommended,
    #[serde(rename = "FASTEST")]
    Fastest,
    #[serde(rename = "CHEAPEST")]
    Cheapest,
    #[serde(rename = "SAFEST")]
    Safest,
}

impl Default for Order {
    fn default() -> Order {
        Self::Recommended
    }
}

