/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Route : A route describing a transfer form a token to another



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Route {
    /// Unique identifier of the route
    #[serde(rename = "id")]
    pub id: String,
    /// The id of the sending chain
    #[serde(rename = "fromChainId")]
    pub from_chain_id: f32,
    /// The amount that should be transferred in USD
    #[serde(rename = "fromAmountUSD")]
    pub from_amount_usd: String,
    /// The amount that should be transferred
    #[serde(rename = "fromAmount")]
    pub from_amount: String,
    #[serde(rename = "fromToken")]
    pub from_token: Box<crate::models::Token>,
    /// The id of the receiving chain
    #[serde(rename = "toChainId")]
    pub to_chain_id: f32,
    /// The estimated resulting amount of the `toToken` in USD as float with two decimals
    #[serde(rename = "toAmountUSD")]
    pub to_amount_usd: String,
    /// The estimated resulting amount of the `toToken` including all decimals
    #[serde(rename = "toAmount")]
    pub to_amount: String,
    /// The minimal resultung amount of the `toToken` including all decimals
    #[serde(rename = "toAmountMin")]
    pub to_amount_min: String,
    #[serde(rename = "toToken")]
    pub to_token: Box<crate::models::Token>,
    /// Aggregation of th eunderlying gas costs in USD
    #[serde(rename = "gasCostUSD", skip_serializing_if = "Option::is_none")]
    pub gas_cost_usd: Option<String>,
    /// The steps required to fulfill the transfer
    #[serde(rename = "steps")]
    pub steps: Vec<crate::models::Step>,
    /// The sending wallet address
    #[serde(rename = "fromAddress", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,
    /// The receiving wallet address
    #[serde(rename = "toAddress", skip_serializing_if = "Option::is_none")]
    pub to_address: Option<String>,
    /// Whether a chain switch is part of the route
    #[serde(rename = "containsSwitchChain", skip_serializing_if = "Option::is_none")]
    pub contains_switch_chain: Option<bool>,
}

impl Route {
    /// A route describing a transfer form a token to another
    pub fn new(id: String, from_chain_id: f32, from_amount_usd: String, from_amount: String, from_token: crate::models::Token, to_chain_id: f32, to_amount_usd: String, to_amount: String, to_amount_min: String, to_token: crate::models::Token, steps: Vec<crate::models::Step>) -> Route {
        Route {
            id,
            from_chain_id,
            from_amount_usd,
            from_amount,
            from_token: Box::new(from_token),
            to_chain_id,
            to_amount_usd,
            to_amount,
            to_amount_min,
            to_token: Box::new(to_token),
            gas_cost_usd: None,
            steps,
            from_address: None,
            to_address: None,
            contains_switch_chain: None,
        }
    }
}


