/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StatusResponse : The current status of a transfer



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "sending")]
    pub sending: Box<crate::models::TransactionInfo>,
    #[serde(rename = "receiving", skip_serializing_if = "Option::is_none")]
    pub receiving: Option<Box<crate::models::TransactionInfo>>,
    /// The current status of the transfer. Can be `PENDING`, `DONE`, `NOT_FOUND` or `FAILED`
    #[serde(rename = "status")]
    pub status: Status,
    /// A more specific substatus. This is available for PENDING and DONE statuses. More information can be found here: https://docs.li.fi/more-integration-options/li.fi-api/checking-the-status-of-a-transaction
    #[serde(rename = "substatus", skip_serializing_if = "Option::is_none")]
    pub substatus: Option<Substatus>,
    /// The tool used for this transfer
    #[serde(rename = "tool")]
    pub tool: String,
}

impl StatusResponse {
    /// The current status of a transfer
    pub fn new(sending: crate::models::TransactionInfo, status: Status, tool: String) -> StatusResponse {
        StatusResponse {
            sending: Box::new(sending),
            receiving: None,
            status,
            substatus: None,
            tool,
        }
    }
}

/// The current status of the transfer. Can be `PENDING`, `DONE`, `NOT_FOUND` or `FAILED`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "INVALID")]
    Invalid,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "DONE")]
    Done,
    #[serde(rename = "FAILED")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::NotFound
    }
}
/// A more specific substatus. This is available for PENDING and DONE statuses. More information can be found here: https://docs.li.fi/more-integration-options/li.fi-api/checking-the-status-of-a-transaction
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Substatus {
    #[serde(rename = "WAIT_SOURCE_CONFIRMATIONS")]
    WaitSourceConfirmations,
    #[serde(rename = "WAIT_DESTINATION_TRANSACTION")]
    WaitDestinationTransaction,
    #[serde(rename = "BRIDGE_NOT_AVAILABLE")]
    BridgeNotAvailable,
    #[serde(rename = "CHAIN_NOT_AVAILABLE")]
    ChainNotAvailable,
    #[serde(rename = "NOT_PROCESSABLE_REFUND_NEEDED")]
    NotProcessableRefundNeeded,
    #[serde(rename = "REFUND_IN_PROGRESS")]
    RefundInProgress,
    #[serde(rename = "UNKNOWN_ERROR")]
    UnknownError,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "PARTIAL")]
    Partial,
    #[serde(rename = "REFUNDED")]
    Refunded,
}

impl Default for Substatus {
    fn default() -> Substatus {
        Self::WaitSourceConfirmations
    }
}

