/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequestEstimate {
    #[serde(rename = "fromAmount", skip_serializing_if = "Option::is_none")]
    pub from_amount: Option<String>,
    #[serde(rename = "toAmount", skip_serializing_if = "Option::is_none")]
    pub to_amount: Option<String>,
    #[serde(rename = "toAmountMin", skip_serializing_if = "Option::is_none")]
    pub to_amount_min: Option<String>,
    #[serde(rename = "approvalAddress", skip_serializing_if = "Option::is_none")]
    pub approval_address: Option<String>,
    #[serde(rename = "feeCosts", skip_serializing_if = "Option::is_none")]
    pub fee_costs: Option<Vec<crate::models::StepRequestEstimateFeeCostsInner>>,
    #[serde(rename = "gasCosts", skip_serializing_if = "Option::is_none")]
    pub gas_costs: Option<Vec<crate::models::StepRequestEstimateGasCostsInner>>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::StepRequestEstimateData>>,
}

impl StepRequestEstimate {
    pub fn new() -> StepRequestEstimate {
        StepRequestEstimate {
            from_amount: None,
            to_amount: None,
            to_amount_min: None,
            approval_address: None,
            fee_costs: None,
            gas_costs: None,
            data: None,
        }
    }
}


