/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StepRequest : A step object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Box<crate::models::StepRequestAction>>,
    #[serde(rename = "estimate", skip_serializing_if = "Option::is_none")]
    pub estimate: Option<Box<crate::models::StepRequestEstimate>>,
    #[serde(rename = "integrator", skip_serializing_if = "Option::is_none")]
    pub integrator: Option<String>,
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Box<crate::models::StepRequestExecution>>,
}

impl StepRequest {
    /// A step object
    pub fn new() -> StepRequest {
        StepRequest {
            id: None,
            r#type: None,
            tool: None,
            action: None,
            estimate: None,
            integrator: None,
            execution: None,
        }
    }
}


