/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequestEstimateGasCostsInner {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "estimate", skip_serializing_if = "Option::is_none")]
    pub estimate: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "amountUSD", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<crate::models::StepRequestEstimateGasCostsInnerToken>>,
}

impl StepRequestEstimateGasCostsInner {
    pub fn new() -> StepRequestEstimateGasCostsInner {
        StepRequestEstimateGasCostsInner {
            r#type: None,
            price: None,
            estimate: None,
            limit: None,
            amount: None,
            amount_usd: None,
            token: None,
        }
    }
}


