/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequestEstimateDataBid {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    #[serde(rename = "router", skip_serializing_if = "Option::is_none")]
    pub router: Option<String>,
    #[serde(rename = "initiator", skip_serializing_if = "Option::is_none")]
    pub initiator: Option<String>,
    #[serde(rename = "sendingChainId", skip_serializing_if = "Option::is_none")]
    pub sending_chain_id: Option<f32>,
    #[serde(rename = "sendingAssetId", skip_serializing_if = "Option::is_none")]
    pub sending_asset_id: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "receivingChainId", skip_serializing_if = "Option::is_none")]
    pub receiving_chain_id: Option<f32>,
    #[serde(rename = "receivingAssetId", skip_serializing_if = "Option::is_none")]
    pub receiving_asset_id: Option<String>,
    #[serde(rename = "amountReceived", skip_serializing_if = "Option::is_none")]
    pub amount_received: Option<String>,
    #[serde(rename = "receivingAddress", skip_serializing_if = "Option::is_none")]
    pub receiving_address: Option<String>,
    #[serde(rename = "transactionId", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "expiry", skip_serializing_if = "Option::is_none")]
    pub expiry: Option<f32>,
    #[serde(rename = "callDataHash", skip_serializing_if = "Option::is_none")]
    pub call_data_hash: Option<String>,
    #[serde(rename = "callTo", skip_serializing_if = "Option::is_none")]
    pub call_to: Option<String>,
    #[serde(rename = "encryptedCallData", skip_serializing_if = "Option::is_none")]
    pub encrypted_call_data: Option<String>,
    #[serde(rename = "sendingChainTxManagerAddress", skip_serializing_if = "Option::is_none")]
    pub sending_chain_tx_manager_address: Option<String>,
    #[serde(rename = "receivingChainTxManagerAddress", skip_serializing_if = "Option::is_none")]
    pub receiving_chain_tx_manager_address: Option<String>,
    #[serde(rename = "bidExpiry", skip_serializing_if = "Option::is_none")]
    pub bid_expiry: Option<f32>,
}

impl StepRequestEstimateDataBid {
    pub fn new() -> StepRequestEstimateDataBid {
        StepRequestEstimateDataBid {
            user: None,
            router: None,
            initiator: None,
            sending_chain_id: None,
            sending_asset_id: None,
            amount: None,
            receiving_chain_id: None,
            receiving_asset_id: None,
            amount_received: None,
            receiving_address: None,
            transaction_id: None,
            expiry: None,
            call_data_hash: None,
            call_to: None,
            encrypted_call_data: None,
            sending_chain_tx_manager_address: None,
            receiving_chain_tx_manager_address: None,
            bid_expiry: None,
        }
    }
}


