/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Step : Object that represents one step of a `Route`



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Step {
    /// Unique identifier of the step
    #[serde(rename = "id")]
    pub id: String,
    /// The type of the step
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The tool used for this step. E.g. `connext`
    #[serde(rename = "tool")]
    pub tool: String,
    #[serde(rename = "action")]
    pub action: Box<crate::models::Action>,
    #[serde(rename = "estimate", skip_serializing_if = "Option::is_none")]
    pub estimate: Option<Box<crate::models::Estimate>>,
    /// A string containing tracking information about the integrator of the API
    #[serde(rename = "integrator", skip_serializing_if = "Option::is_none")]
    pub integrator: Option<String>,
    /// A string containing tracking information about the referrer of the integrator
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    /// An objection containing status information about the execution
    #[serde(rename = "execution", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Option<serde_json::Value>>,
    /// An ether.js TransactionRequest that can be triggered using a wallet provider. (https://docs.ethers.io/v5/api/providers/types/#providers-TransactionRequest)
    #[serde(rename = "transactionRequest", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transaction_request: Option<Option<serde_json::Value>>,
}

impl Step {
    /// Object that represents one step of a `Route`
    pub fn new(id: String, r#type: Type, tool: String, action: crate::models::Action) -> Step {
        Step {
            id,
            r#type,
            tool,
            action: Box::new(action),
            estimate: None,
            integrator: None,
            referrer: None,
            execution: None,
            transaction_request: None,
        }
    }
}

/// The type of the step
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "swap")]
    Swap,
    #[serde(rename = "cross")]
    Cross,
    #[serde(rename = "lifi")]
    Lifi,
}

impl Default for Type {
    fn default() -> Type {
        Self::Swap
    }
}

