/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequestAction {
    #[serde(rename = "fromChainId", skip_serializing_if = "Option::is_none")]
    pub from_chain_id: Option<f32>,
    #[serde(rename = "toChainId", skip_serializing_if = "Option::is_none")]
    pub to_chain_id: Option<f32>,
    #[serde(rename = "fromToken", skip_serializing_if = "Option::is_none")]
    pub from_token: Option<Box<crate::models::StepRequestActionFromToken>>,
    #[serde(rename = "toToken", skip_serializing_if = "Option::is_none")]
    pub to_token: Option<Box<crate::models::StepRequestActionFromToken>>,
    #[serde(rename = "fromAmount", skip_serializing_if = "Option::is_none")]
    pub from_amount: Option<String>,
    #[serde(rename = "fromAddress", skip_serializing_if = "Option::is_none")]
    pub from_address: Option<String>,
    #[serde(rename = "toAddress", skip_serializing_if = "Option::is_none")]
    pub to_address: Option<String>,
    #[serde(rename = "slippage", skip_serializing_if = "Option::is_none")]
    pub slippage: Option<f32>,
}

impl StepRequestAction {
    pub fn new() -> StepRequestAction {
        StepRequestAction {
            from_chain_id: None,
            to_chain_id: None,
            from_token: None,
            to_token: None,
            from_amount: None,
            from_address: None,
            to_address: None,
            slippage: None,
        }
    }
}


