/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRequestEstimateFeeCostsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<crate::models::StepRequestActionFromToken>>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "amountUSD", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<bool>,
}

impl StepRequestEstimateFeeCostsInner {
    pub fn new() -> StepRequestEstimateFeeCostsInner {
        StepRequestEstimateFeeCostsInner {
            name: None,
            description: None,
            percentage: None,
            token: None,
            amount: None,
            amount_usd: None,
            included: None,
        }
    }
}


