/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedChains {
    /// Supported `from` chain
    #[serde(rename = "fromChainId", skip_serializing_if = "Option::is_none")]
    pub from_chain_id: Option<String>,
    /// Supported `to` chain
    #[serde(rename = "toChainId", skip_serializing_if = "Option::is_none")]
    pub to_chain_id: Option<String>,
}

impl SupportedChains {
    pub fn new() -> SupportedChains {
        SupportedChains {
            from_chain_id: None,
            to_chain_id: None,
        }
    }
}


