/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Token : Representation of a Token



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    /// Address of the token
    #[serde(rename = "address")]
    pub address: String,
    /// Number of decimals the token uses
    #[serde(rename = "decimals")]
    pub decimals: f32,
    /// Symbol of the token
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Id of the token's chain
    #[serde(rename = "chainId")]
    pub chain_id: f32,
    /// Identifier for the token
    #[serde(rename = "coinKey", skip_serializing_if = "Option::is_none")]
    pub coin_key: Option<String>,
    /// Name of the token
    #[serde(rename = "name")]
    pub name: String,
    /// Logo of the token
    #[serde(rename = "logoURI", skip_serializing_if = "Option::is_none")]
    pub logo_uri: Option<String>,
    /// Token price in USD
    #[serde(rename = "priceUSD", skip_serializing_if = "Option::is_none")]
    pub price_usd: Option<String>,
}

impl Token {
    /// Representation of a Token
    pub fn new(address: String, decimals: f32, symbol: String, chain_id: f32, name: String) -> Token {
        Token {
            address,
            decimals,
            symbol,
            chain_id,
            coin_key: None,
            name,
            logo_uri: None,
            price_usd: None,
        }
    }
}


