/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenBalances {
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<crate::models::Token>,
    /// Fee amount in tokens
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// Fee amount in USD
    #[serde(rename = "amountUsd", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
}

impl TokenBalances {
    pub fn new() -> TokenBalances {
        TokenBalances {
            token: None,
            amount: None,
            amount_usd: None,
        }
    }
}


