/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TokenRequest : The address and chain id of the requested token



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRequest {
    /// Id of the chain that contains the token
    #[serde(rename = "chainId")]
    pub chain_id: f32,
    /// Address of the token on the requested chain
    #[serde(rename = "address")]
    pub address: String,
}

impl TokenRequest {
    /// The address and chain id of the requested token
    pub fn new(chain_id: f32, address: String) -> TokenRequest {
        TokenRequest {
            chain_id,
            address,
        }
    }
}


