/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ToolError : Describes why a certain operation (like a quote request) failed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolError {
    /// The type of error that occurred.
    #[serde(rename = "errorType", skip_serializing_if = "Option::is_none")]
    pub error_type: Option<ErrorType>,
    /// The error code.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<Code>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Box<crate::models::Action>>,
    /// The tool that emitted the error.
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    /// A human-readable message describing the error.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ToolError {
    /// Describes why a certain operation (like a quote request) failed.
    pub fn new() -> ToolError {
        ToolError {
            error_type: None,
            code: None,
            action: None,
            tool: None,
            message: None,
        }
    }
}

/// The type of error that occurred.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorType {
    #[serde(rename = "NO_QUOTE")]
    NoQuote,
}

impl Default for ErrorType {
    fn default() -> ErrorType {
        Self::NoQuote
    }
}
/// The error code.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "NO_POSSIBLE_ROUTE")]
    NoPossibleRoute,
    #[serde(rename = "INSUFFICIENT_LIQUIDITY")]
    InsufficientLiquidity,
    #[serde(rename = "TOOL_TIMEOUT")]
    ToolTimeout,
    #[serde(rename = "UNKNOWN_ERROR")]
    UnknownError,
    #[serde(rename = "RPC_ERROR")]
    RpcError,
    #[serde(rename = "AMOUNT_TOO_LOW")]
    AmountTooLow,
    #[serde(rename = "AMOUNT_TOO_HIGH")]
    AmountTooHigh,
    #[serde(rename = "FEES_HIGHER_THAN_AMOUNT")]
    FeesHigherThanAmount,
    #[serde(rename = "DIFFERENT_RECIPIENT_NOT_SUPPORTED")]
    DifferentRecipientNotSupported,
    #[serde(rename = "TOOL_SPECIFIC_ERROR")]
    ToolSpecificError,
    #[serde(rename = "CANNOT_GUARANTEE_MIN_AMOUNT")]
    CannotGuaranteeMinAmount,
    #[serde(rename = "RATE_LIMIT_EXCEEDED")]
    RateLimitExceeded,
}

impl Default for Code {
    fn default() -> Code {
        Self::NoPossibleRoute
    }
}

