/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tools {
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<Vec<crate::models::Exchange>>,
    #[serde(rename = "bridges", skip_serializing_if = "Option::is_none")]
    pub bridges: Option<Vec<crate::models::Bridge>>,
}

impl Tools {
    pub fn new() -> Tools {
        Tools {
            exchanges: None,
            bridges: None,
        }
    }
}


