/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionInfo : A transaction info object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInfo {
    /// The hash of the transaction
    #[serde(rename = "txHash")]
    pub tx_hash: String,
    /// Link to a block explorer showing the transaction
    #[serde(rename = "txLink")]
    pub tx_link: String,
    /// The amount of the transaction
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
    /// The id of the chain
    #[serde(rename = "chainId")]
    pub chain_id: f32,
    #[serde(rename = "gasToken", skip_serializing_if = "Option::is_none")]
    pub gas_token: Option<Box<crate::models::Token>>,
    /// The amount of the gas that was paid
    #[serde(rename = "gasAmount", skip_serializing_if = "Option::is_none")]
    pub gas_amount: Option<String>,
    /// The amount of the gas that was paid in USD
    #[serde(rename = "gasAmountUSD", skip_serializing_if = "Option::is_none")]
    pub gas_amount_usd: Option<String>,
    /// The price of the gas
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    /// The amount of the gas that was used
    #[serde(rename = "gasUsed", skip_serializing_if = "Option::is_none")]
    pub gas_used: Option<String>,
}

impl TransactionInfo {
    /// A transaction info object
    pub fn new(tx_hash: String, tx_link: String, amount: String, token: crate::models::Token, chain_id: f32) -> TransactionInfo {
        TransactionInfo {
            tx_hash,
            tx_link,
            amount,
            token: Box::new(token),
            chain_id,
            gas_token: None,
            gas_amount: None,
            gas_amount_usd: None,
            gas_price: None,
            gas_used: None,
        }
    }
}


