/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxInfo {
    #[serde(rename = "txHash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    #[serde(rename = "txLink", skip_serializing_if = "Option::is_none")]
    pub tx_link: Option<String>,
    /// The amount of token that will be / has been relayed
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<crate::models::Token>>,
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<f32>,
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<f32>,
}

impl TxInfo {
    pub fn new() -> TxInfo {
        TxInfo {
            tx_hash: None,
            tx_link: None,
            amount: None,
            token: None,
            chain_id: None,
            block: None,
        }
    }
}


