/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnavailableRoutes {
    /// An object containing information about routes that were intentionally filtered out.
    #[serde(rename = "filteredOut", skip_serializing_if = "Option::is_none")]
    pub filtered_out: Option<Vec<crate::models::UnavailableRoutesFilteredOutInner>>,
    /// An object containing information about failed routes.
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<Vec<crate::models::UnavailableRoutesFailedInner>>,
}

impl UnavailableRoutes {
    pub fn new() -> UnavailableRoutes {
        UnavailableRoutes {
            filtered_out: None,
            failed: None,
        }
    }
}


