/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnavailableRoutesFilteredOutInner {
    /// The complete representation of the attempted route.
    #[serde(rename = "overallPath", skip_serializing_if = "Option::is_none")]
    pub overall_path: Option<String>,
    /// Out best attempt at describing the failure.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl UnavailableRoutesFilteredOutInner {
    pub fn new() -> UnavailableRoutesFilteredOutInner {
        UnavailableRoutesFilteredOutInner {
            overall_path: None,
            reason: None,
        }
    }
}


