/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnavailableRoutesFailedInner {
    /// The complete representation of the attempted route.
    #[serde(rename = "overallPath", skip_serializing_if = "Option::is_none")]
    pub overall_path: Option<String>,
    /// An object with all subpaths that generated one or more errors
    #[serde(rename = "subpaths", skip_serializing_if = "Option::is_none")]
    pub subpaths: Option<::std::collections::HashMap<String, crate::models::ToolError>>,
}

impl UnavailableRoutesFailedInner {
    pub fn new() -> UnavailableRoutesFailedInner {
        UnavailableRoutesFailedInner {
            overall_path: None,
            subpaths: None,
        }
    }
}


