/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WalletAnalyticsResponse : All transactions for a wallet address



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletAnalyticsResponse {
    /// Wallet address
    #[serde(rename = "walletAddress")]
    pub wallet_address: String,
    #[serde(rename = "transactions")]
    pub transactions: Vec<crate::models::StatusResponse>,
}

impl WalletAnalyticsResponse {
    /// All transactions for a wallet address
    pub fn new(wallet_address: String, transactions: Vec<crate::models::StatusResponse>) -> WalletAnalyticsResponse {
        WalletAnalyticsResponse {
            wallet_address,
            transactions,
        }
    }
}


