/*
 * LI.FI API
 *
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method [`analytics_transfers_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnalyticsTransfersGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`analytics_wallets_wallet_address_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnalyticsWalletsWalletAddressGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`calldata_parse_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CalldataParseGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`chains_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChainsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`connections_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConnectionsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gas_refetch_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GasRefetchGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gas_status_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GasStatusGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`gas_suggestion_chain_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GasSuggestionChainGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`integrators_integrator_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IntegratorsIntegratorIdGetError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`integrators_integrator_id_withdraw_chain_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IntegratorsIntegratorIdWithdrawChainIdGetError {
    Status400(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quote_contract_call_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteContractCallPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quote_contract_calls_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteContractCallsPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quote_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteGetError {
    Status400(),
    Status404(crate::models::QuoteGet404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`status_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatusGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`token_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TokenGetError {
    Status400(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`tokens_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TokensGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`tools_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ToolsGetError {
    UnknownValue(serde_json::Value),
}


/// This endpoint can be used to retrieve a list of transfers filtered by certain properties. Returns a maximum of 1000 transfers.
pub async fn analytics_transfers_get(configuration: &configuration::Configuration, integrator: &str, wallet: Option<&str>, status: Option<&str>, from_timestamp: Option<f32>, to_timestamp: Option<f32>) -> Result<serde_json::Value, Error<AnalyticsTransfersGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/analytics/transfers", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("integrator", &integrator.to_string())]);
    if let Some(ref local_var_str) = wallet {
        local_var_req_builder = local_var_req_builder.query(&[("wallet", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = status {
        local_var_req_builder = local_var_req_builder.query(&[("status", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = from_timestamp {
        local_var_req_builder = local_var_req_builder.query(&[("fromTimestamp", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = to_timestamp {
        local_var_req_builder = local_var_req_builder.query(&[("toTimestamp", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<AnalyticsTransfersGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to get all transactions for a wallet.
pub async fn analytics_wallets_wallet_address_get(configuration: &configuration::Configuration, wallet_address: &str, integrator: &str, from_timestamp: Option<i32>, to_timestamp: Option<i32>, x_lifi_api_key: Option<&str>) -> Result<crate::models::WalletAnalyticsResponse, Error<AnalyticsWalletsWalletAddressGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/analytics/wallets/{wallet_address}", local_var_configuration.base_path, wallet_address=crate::apis::urlencode(wallet_address));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("integrator", &integrator.to_string())]);
    if let Some(ref local_var_str) = from_timestamp {
        local_var_req_builder = local_var_req_builder.query(&[("fromTimestamp", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = to_timestamp {
        local_var_req_builder = local_var_req_builder.query(&[("toTimestamp", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<AnalyticsWalletsWalletAddressGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint allows to pass transaction call data. It will then parse the call data based on known and on-chain ABIs to provide a JSON overview of the internal transaction information.
pub async fn calldata_parse_get(configuration: &configuration::Configuration, call_data: &str, chain_id: Option<&str>, x_lifi_api_key: Option<&str>) -> Result<(), Error<CalldataParseGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/calldata/parse", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = chain_id {
        local_var_req_builder = local_var_req_builder.query(&[("chainId", &local_var_str.to_string())]);
    }
    local_var_req_builder = local_var_req_builder.query(&[("callData", &call_data.to_string())]);
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<CalldataParseGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// If you want to learn more about how to use this endpoint please have a look at our [guide](https://docs.li.fi/more-integration-options/li.fi-api/requesting-supported-chains).
pub async fn chains_get(configuration: &configuration::Configuration, chain_types: Option<&str>, x_lifi_api_key: Option<&str>) -> Result<crate::models::ChainsResponse, Error<ChainsGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/chains", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = chain_types {
        local_var_req_builder = local_var_req_builder.query(&[("chainTypes", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<ChainsGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint gives information about all possible tranfers between chains. Since the result can be very large it is required to filter by at least a chain, a token, a bridge, or an exchange. Information about which chains and tokens are supported can be taken from the response of the /chains endpoint. Information about which bridges and exchanges are supported can be taken from the response of the /tools endpoint.
pub async fn connections_get(configuration: &configuration::Configuration, from_chain: Option<&str>, to_chain: Option<&str>, from_token: Option<&str>, to_token: Option<&str>, chain_types: Option<&str>, allow_bridges: Option<Vec<String>>, x_lifi_api_key: Option<&str>) -> Result<crate::models::ConnectionsResponse, Error<ConnectionsGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/connections", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = from_chain {
        local_var_req_builder = local_var_req_builder.query(&[("fromChain", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = to_chain {
        local_var_req_builder = local_var_req_builder.query(&[("toChain", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = from_token {
        local_var_req_builder = local_var_req_builder.query(&[("fromToken", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = to_token {
        local_var_req_builder = local_var_req_builder.query(&[("toToken", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = chain_types {
        local_var_req_builder = local_var_req_builder.query(&[("chainTypes", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = allow_bridges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("allowBridges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("allowBridges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<ConnectionsGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn gas_refetch_get(configuration: &configuration::Configuration, tx_hash: &str, chain_id: &str, x_lifi_api_key: Option<&str>) -> Result<crate::models::LiFuelStatus, Error<GasRefetchGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gas/refetch", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("txHash", &tx_hash.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("chainId", &chain_id.to_string())]);
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GasRefetchGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn gas_status_get(configuration: &configuration::Configuration, tx_hash: &str, x_lifi_api_key: Option<&str>) -> Result<crate::models::LiFuelStatus, Error<GasStatusGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gas/status", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("txHash", &tx_hash.to_string())]);
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GasStatusGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Endpoint to retrieve a suggestion on how much gas is needed on the requested chain. The suggestion is based on the average price of 10 approvals and 10 uniswap based swaps via LI.FI on the specified chain. If `fromChain` and `fromToken` are specified, the result will contain information about how much `fromToken` amount the user has to send to receive the suggested gas amount on the requested chain.
pub async fn gas_suggestion_chain_get(configuration: &configuration::Configuration, chain: &str, from_chain: Option<&str>, from_token: Option<&str>, x_lifi_api_key: Option<&str>) -> Result<(), Error<GasSuggestionChainGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/gas/suggestion/{chain}", local_var_configuration.base_path, chain=crate::apis::urlencode(chain));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = from_chain {
        local_var_req_builder = local_var_req_builder.query(&[("fromChain", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = from_token {
        local_var_req_builder = local_var_req_builder.query(&[("fromToken", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<GasSuggestionChainGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to request all integrator's collected fees data by tokens for all supported chains. The endpoint returns an `Integrator` object which contains the integrator name (or the address if the name wasn't found in configurations) and an array of fee balances for all supported chains.
pub async fn integrators_integrator_id_get(configuration: &configuration::Configuration, integrator_id: &str, x_lifi_api_key: Option<&str>) -> Result<crate::models::IntegratorResponse, Error<IntegratorsIntegratorIdGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/integrators/{integratorId}", local_var_configuration.base_path, integratorId=crate::apis::urlencode(integrator_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<IntegratorsIntegratorIdGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to get transaction request for withdrawing integrator's collected fees the specified chain. If a list of token addresses is provided, the generated transaction will only withdraw the specified funds. If there is no collected fees for the provided token's addresses, the `400` error will be thrown. The endpoint returns a `IntegratorWithdrawalTransactionResponse` object which contains the transaction request.
pub async fn integrators_integrator_id_withdraw_chain_id_get(configuration: &configuration::Configuration, integrator_id: &str, chain_id: &str, token_addresses: Option<Vec<String>>, x_lifi_api_key: Option<&str>) -> Result<crate::models::IntegratorWithdrawalResponse, Error<IntegratorsIntegratorIdWithdrawChainIdGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/integrators/{integratorId}/withdraw/{chainId}", local_var_configuration.base_path, integratorId=crate::apis::urlencode(integrator_id), chainId=crate::apis::urlencode(chain_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = token_addresses {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("tokenAddresses".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("tokenAddresses", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<IntegratorsIntegratorIdWithdrawChainIdGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint has been deprecated in favour of /quote/contractCalls.
pub async fn quote_contract_call_post(configuration: &configuration::Configuration, x_lifi_api_key: Option<&str>, contract_call_request: Option<crate::models::ContractCallRequest>) -> Result<crate::models::Tools, Error<QuoteContractCallPostError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/quote/contractCall", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&contract_call_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<QuoteContractCallPostError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to bridge tokens, swap them and perform a number or arbitrary contract calls on the destination chain. You can find an example of it [here](https://github.com/lifinance/sdk/tree/main/examples). This functionality is currently in beta. While we've worked hard to ensure its stability and functionality, there might still be some rough edges.
pub async fn quote_contract_calls_post(configuration: &configuration::Configuration, x_lifi_api_key: Option<&str>, contract_calls_request: Option<crate::models::ContractCallsRequest>) -> Result<crate::models::Tools, Error<QuoteContractCallsPostError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/quote/contractCalls", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }
    local_var_req_builder = local_var_req_builder.json(&contract_calls_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<QuoteContractCallsPostError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to request a quote for a transfer of one token to another, cross chain or not. The endpoint returns a `Step` object which contains information about the estimated result as well as a `transactionRequest` which can directly be sent to your wallet. The estimated result can be found inside the `estimate`, containing the estimated `toAmount` of the requested `Token` and the `toAmountMin`, which is the guaranteed minimum value that the transfer will yield including slippage. If you want to learn more about how to use this endpoint please have a look at our [guide](https://docs.li.fi/more-integration-options/li.fi-api/requesting-a-quote).
pub async fn quote_get(configuration: &configuration::Configuration, from_chain: &str, to_chain: &str, from_token: &str, to_token: &str, from_address: &str, from_amount: &str, to_address: Option<&str>, order: Option<&str>, slippage: Option<f32>, integrator: Option<&str>, fee: Option<f32>, referrer: Option<&str>, allow_bridges: Option<Vec<crate::models::QuoteBridgesEnum>>, allow_exchanges: Option<Vec<crate::models::QuoteExchangesEnum>>, deny_bridges: Option<Vec<crate::models::QuoteBridgesEnum>>, deny_exchanges: Option<Vec<crate::models::QuoteExchangesEnum>>, prefer_bridges: Option<Vec<crate::models::QuoteBridgesEnum>>, prefer_exchanges: Option<Vec<crate::models::QuoteExchangesEnum>>, allow_destination_call: Option<bool>, max_price_impact: Option<f32>, x_lifi_api_key: Option<&str>) -> Result<crate::models::Step, Error<QuoteGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/quote", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("fromChain", &from_chain.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("toChain", &to_chain.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("fromToken", &from_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("toToken", &to_token.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("fromAddress", &from_address.to_string())]);
    if let Some(ref local_var_str) = to_address {
        local_var_req_builder = local_var_req_builder.query(&[("toAddress", &local_var_str.to_string())]);
    }
    local_var_req_builder = local_var_req_builder.query(&[("fromAmount", &from_amount.to_string())]);
    if let Some(ref local_var_str) = order {
        local_var_req_builder = local_var_req_builder.query(&[("order", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = slippage {
        local_var_req_builder = local_var_req_builder.query(&[("slippage", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = integrator {
        local_var_req_builder = local_var_req_builder.query(&[("integrator", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = fee {
        local_var_req_builder = local_var_req_builder.query(&[("fee", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = referrer {
        local_var_req_builder = local_var_req_builder.query(&[("referrer", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = allow_bridges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("allowBridges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("allowBridges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = allow_exchanges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("allowExchanges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("allowExchanges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = deny_bridges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("denyBridges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("denyBridges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = deny_exchanges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("denyExchanges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("denyExchanges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = prefer_bridges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("preferBridges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("preferBridges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = prefer_exchanges {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("preferExchanges".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("preferExchanges", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_str) = allow_destination_call {
        local_var_req_builder = local_var_req_builder.query(&[("allowDestinationCall", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = max_price_impact {
        local_var_req_builder = local_var_req_builder.query(&[("maxPriceImpact", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<QuoteGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

use crate::models::BridgesEnum;

/// Cross chain transfers might take a while to complete. Waiting on the transaction on the sending chain doesn't help here. For this reason we build a simple endpoint that let's you check the status of your transfer. Important: The endpoint returns a `200` successful response even if the transaction can not be found. This behavior accounts for the case that the transaction hash is valid but the transaction has not been mined yet. While non of the parameters `fromChain`, `toChain` and `bridge` are required, passing the `fromChain` parameter will speed up the request and is therefore encouraged. If you want to learn more about how to use this endpoint please have a look at our [guide](https://docs.li.fi/more-integration-options/li.fi-api/checking-the-status-of-a-transaction).
pub async fn status_get(configuration: &configuration::Configuration, tx_hash: &str, bridge: Option<BridgesEnum>, from_chain: Option<&str>, to_chain: Option<&str>, x_lifi_api_key: Option<&str>) -> Result<crate::models::StatusResponse, Error<StatusGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/status", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("txHash", &tx_hash.to_string())]);
    if let Some(ref local_var_str) = bridge {
        local_var_req_builder = local_var_req_builder.query(&[("bridge", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = from_chain {
        local_var_req_builder = local_var_req_builder.query(&[("fromChain", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = to_chain {
        local_var_req_builder = local_var_req_builder.query(&[("toChain", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<StatusGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to get more information about a token by its address or symbol and its chain. If you want to learn more about how to use this endpoint please have a look at our [guide](https://docs.li.fi/more-integration-options/li.fi-api/getting-token-information).
pub async fn token_get(configuration: &configuration::Configuration, chain: &str, token: &str, x_lifi_api_key: Option<&str>) -> Result<Vec<crate::models::Token>, Error<TokenGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/token", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("chain", &chain.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("token", &token.to_string())]);
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<TokenGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to fetch all tokens known to the LI.FI services.
pub async fn tokens_get(configuration: &configuration::Configuration, chains: Option<&str>, chain_types: Option<&str>, x_lifi_api_key: Option<&str>) -> Result<crate::models::TokensGet200Response, Error<TokensGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/tokens", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = chains {
        local_var_req_builder = local_var_req_builder.query(&[("chains", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = chain_types {
        local_var_req_builder = local_var_req_builder.query(&[("chainTypes", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<TokensGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// This endpoint can be used to get information about the bridges and exchanges available trough our service
pub async fn tools_get(configuration: &configuration::Configuration, x_lifi_api_key: Option<&str>) -> Result<crate::models::Tools, Error<ToolsGetError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/tools", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_lifi_api_key {
        local_var_req_builder = local_var_req_builder.header("x-lifi-api-key", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<ToolsGetError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

// MARK: - Tests
#[cfg(test)]
mod tests {
    use super::*; // Import everything from the parent module
    use crate::apis::configuration::Configuration;

    #[tokio::test] // Mark this function as a test to be run asynchronously
    async fn should_get_a_quote() {
        // Assume you've a create_configuration function which returns a Configuration object
        let config = Configuration::new();

        // Make your request. Ensure quote_get is implemented to be asynchronous (using async keyword)
        let res = quote_get(
            &config, 
            "1", 
            "1", 
            "ETH", 
            "USDC", 
            "0x492804d7740150378be8d4bbf8ce012c5497dea9", 
            "1000000000000000000", 
            None, // to_address
            None, // order
            None, // slippage
            None, // integrator
            None, // fee
            None, // referrer
            None, // allow_bridges
            None, // allow_exchanges
            None, // deny_bridges
            None, // deny_exchanges
            None, // prefer_bridges
            None, // prefer_exchanges
            None, // allow_destination_call
            None, // max_price_impact
            None  // x_lifi_api_key
        ).await;

        assert!(res.is_ok(), "Expected result to be Some, got None");
    }
}