/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

/**
* Object describing what happens in a `Step`
*/
export class Action {
    /**
    * The id of the chain where the transfer should start
    */
    'fromChainId': number;
    /**
    * The amount that should be transferred including all decimals
    */
    'fromAmount': string;
    'fromToken': Token;
    /**
    * The id of the chain where the transfer should end
    */
    'toChainId': number;
    'toToken': Token;
    /**
    * The maximum allowed slippage
    */
    'slippage'?: number;
    /**
    * The sending wallet address
    */
    'fromAddress'?: string;
    /**
    * The receiving wallet address
    */
    'toAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromToken",
            "baseName": "fromToken",
            "type": "Token",
            "format": ""
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "toToken",
            "baseName": "toToken",
            "type": "Token",
            "format": ""
        },
        {
            "name": "slippage",
            "baseName": "slippage",
            "type": "number",
            "format": "double"
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Action.attributeTypeMap;
    }

    public constructor() {
    }
}

