/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { z } from 'zod';
import { HttpFile } from '../http/http';

/**
* Object defining which tools should be allowed, denied and preferred
*/
export class AllowDenyPrefer {
    /**
    * Allowed tools
    */
    'allow'?: Array<string>;
    /**
    * Forbidden tools
    */
    'deny'?: Array<string>;
    /**
    * Preferred tools
    */
    'prefer'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "allow",
            "baseName": "allow",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "deny",
            "baseName": "deny",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "prefer",
            "baseName": "prefer",
            "type": "Array<string>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return AllowDenyPrefer.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod() {
        return z.object({
            allow: z.array(z.string()).optional(),
            deny: z.array(z.string()).optional(),
            prefer: z.array(z.string()).optional(),
        });
    }
}

