/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChainMetamaskNativeCurrency } from './ChainMetamaskNativeCurrency';
import { HttpFile } from '../http/http';

/**
* Information about the chain from metamask. Contains data about RPCs and block explorers
*/
export class ChainMetamask {
    'chainId'?: string;
    'blockExplorerUrls'?: Array<string>;
    'chainName'?: string;
    'nativeCurrency'?: ChainMetamaskNativeCurrency;
    'rpcUrls'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "string",
            "format": ""
        },
        {
            "name": "blockExplorerUrls",
            "baseName": "blockExplorerUrls",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "chainName",
            "baseName": "chainName",
            "type": "string",
            "format": ""
        },
        {
            "name": "nativeCurrency",
            "baseName": "nativeCurrency",
            "type": "ChainMetamaskNativeCurrency",
            "format": ""
        },
        {
            "name": "rpcUrls",
            "baseName": "rpcUrls",
            "type": "Array<string>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return ChainMetamask.attributeTypeMap;
    }

    public constructor() {
    }
}

