/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

/**
* A connection from one chain to another defined by tokens that can be exchanged for another.
*/
export class Connection {
    /**
    * The sending chain
    */
    'fromChainId': number;
    /**
    * The receiving chain
    */
    'toChainId': number;
    /**
    * List of possible tokens that can be sent
    */
    'fromTokens': Array<Token>;
    /**
    * List of tokens that can be sent
    */
    'toTokens': Array<Token>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "number",
            "format": ""
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromTokens",
            "baseName": "fromTokens",
            "type": "Array<Token>",
            "format": ""
        },
        {
            "name": "toTokens",
            "baseName": "toTokens",
            "type": "Array<Token>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Connection.attributeTypeMap;
    }

    public constructor() {
    }
}

