/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Object defining instructions on how to perform a cross chain call
*/
export class ContractCallRequest {
    /**
    * The sending chain. Can be the chain id or chain key
    */
    'fromChain': number;
    /**
    * The token that should be transferred. Can be the address or the symbol
    */
    'fromToken': string;
    /**
    * The wallet that will send the transaction and contains the starting token
    */
    'fromAddress': string;
    /**
    * The receiving chain. Can be the chain id or chain key
    */
    'toChain': number;
    /**
    * The token required to perform the contract interation (can be something to stake, donate or to be used as payment)
    */
    'toToken': string;
    /**
    * The amount of token required by the contract interaction. The LI.FI API will try and generate a quote that guarantees at least that amount on the destination chain.
    */
    'toAmount': string;
    /**
    * The address of the contract to interact with
    */
    'toContractAddress': string;
    /**
    * Some contract interactions will output a token. This is the case in things like staking. Omit this parameter if no token should be returned to the user.
    */
    'contractOutputsToken'?: string;
    /**
    * The calldata to be sent to the contract for the interaction on the destination chain.
    */
    'toContractCallData': string;
    /**
    * The estimated gas used by the destination call. If this value is incorrect, the interaction may fail -- choose this carefully!
    */
    'toContractGasLimit': string;
    /**
    * If the approval address is different thant the contract to call, specify that address here
    */
    'toApprovalAddress'?: string;
    /**
    * If the call fails, use this address to send the bridged tokens to. If none is specified, the sending address will be used.
    */
    'toFallbackAddress'?: string;
    /**
    * The maximum allowed slippage for the transaction as a decimal value. 0.005 represents 0.5%.
    */
    'slippage'?: number;
    /**
    * A string containing tracking information about the integrator of the API
    */
    'integrator'?: string;
    /**
    * A string containing tracking information about the referrer of the integrator
    */
    'referrer'?: string;
    /**
    * List of bridges that are allowed for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    */
    'allowBridges'?: Array<string>;
    /**
    * List of bridges that are not allowed for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    */
    'denyBridges'?: Array<string>;
    /**
    * List of bridges that should be preferred for this transaction. Currently available bridges are for example `hop`, `multichain` or `connext`. All supported bridges can be loaded from the /tools endpoint.
    */
    'preferBridges'?: Array<string>;
    /**
    * List of exchanges that are allowed for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    */
    'allowExchanges'?: Array<string>;
    /**
    * List of exchanges that are not allowed for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    */
    'denyExchanges'?: Array<string>;
    /**
    * List of exchanges that should be preferred for this transaction. Currently available exchanges are aggregators such as `1inch`, `paraswap`, `openocean` and `0x` and a lot of dexes.
    */
    'preferExchanges'?: Array<string>;
    /**
    * The price impact threshold above which routes are hidden. As an example, one should specify 0.15 (15%) to hide routes with more than 15% price impact. The default is 10%.
    */
    'maxPriceImpact'?: number;
    /**
    * Whether swaps or other contract calls should be allowed as part of the destination transaction of a bridge transfer. Separate swap transactions on the destination chain are not affected by this flag. By default, parameter is `true`.
    */
    'allowDestinationCall'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromChain",
            "baseName": "fromChain",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromToken",
            "baseName": "fromToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toChain",
            "baseName": "toChain",
            "type": "number",
            "format": ""
        },
        {
            "name": "toToken",
            "baseName": "toToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "toAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractAddress",
            "baseName": "toContractAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractOutputsToken",
            "baseName": "contractOutputsToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractCallData",
            "baseName": "toContractCallData",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractGasLimit",
            "baseName": "toContractGasLimit",
            "type": "string",
            "format": ""
        },
        {
            "name": "toApprovalAddress",
            "baseName": "toApprovalAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toFallbackAddress",
            "baseName": "toFallbackAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "slippage",
            "baseName": "slippage",
            "type": "number",
            "format": "double"
        },
        {
            "name": "integrator",
            "baseName": "integrator",
            "type": "string",
            "format": ""
        },
        {
            "name": "referrer",
            "baseName": "referrer",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowBridges",
            "baseName": "allowBridges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "denyBridges",
            "baseName": "denyBridges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "preferBridges",
            "baseName": "preferBridges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "allowExchanges",
            "baseName": "allowExchanges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "denyExchanges",
            "baseName": "denyExchanges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "preferExchanges",
            "baseName": "preferExchanges",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "maxPriceImpact",
            "baseName": "maxPriceImpact",
            "type": "number",
            "format": "double"
        },
        {
            "name": "allowDestinationCall",
            "baseName": "allowDestinationCall",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContractCallRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

