/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestEstimateDataBid } from './StepRequestEstimateDataBid';
import { HttpFile } from '../http/http';

/**
* Arbitrary data that depends on the the used tool
*/
export class EstimateData {
    'bid'?: StepRequestEstimateDataBid;
    'bidSignature'?: string;
    'gasFeeInReceivingToken'?: string;
    'totalFee'?: string;
    'metaTxRelayerFee'?: string;
    'routerFee'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "bid",
            "baseName": "bid",
            "type": "StepRequestEstimateDataBid",
            "format": ""
        },
        {
            "name": "bidSignature",
            "baseName": "bidSignature",
            "type": "string",
            "format": ""
        },
        {
            "name": "gasFeeInReceivingToken",
            "baseName": "gasFeeInReceivingToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalFee",
            "baseName": "totalFee",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaTxRelayerFee",
            "baseName": "metaTxRelayerFee",
            "type": "string",
            "format": ""
        },
        {
            "name": "routerFee",
            "baseName": "routerFee",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return EstimateData.attributeTypeMap;
    }

    public constructor() {
    }
}

