/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EstimateData } from './EstimateData';
import { FeeCost } from './FeeCost';
import { GasCost } from './GasCost';
import { HttpFile } from '../http/http';
import { z } from 'zod';

/**
* An estimate for the current transfer
*/
export class Estimate {
    /**
    * The amount that should be transferred
    */
    'fromAmount': string;
    /**
    * The estimated resulting amount of the `toToken`
    */
    'toAmount': string;
    /**
    * The minimal outcome of the transfer
    */
    'toAmountMin': string;
    /**
    * The contract address for the approval
    */
    'approvalAddress': string;
    /**
    * Fees included in the transfer
    */
    'feeCosts'?: Array<FeeCost>;
    /**
    * Gas costs included in the transfer
    */
    'gasCosts'?: Array<GasCost>;
    /**
     * The duration of the execution
     */
    'executionDuration': number;
    /**
     * The tool used for this step. E.g. `connext`
     */
    'tool': string;

    'data'?: EstimateData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "toAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmountMin",
            "baseName": "toAmountMin",
            "type": "string",
            "format": ""
        },
        {
            "name": "approvalAddress",
            "baseName": "approvalAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "feeCosts",
            "baseName": "feeCosts",
            "type": "Array<FeeCost>",
            "format": ""
        },
        {
            "name": "gasCosts",
            "baseName": "gasCosts",
            "type": "Array<GasCost>",
            "format": ""
        },
        {
            "name": "executionDuration",
            "baseName": "executionDuration",
            "type": "number",
            "format": ""
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "EstimateData",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Estimate.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod(): z.ZodType<Estimate> {
        return z.object({
            fromAmount: z.string(),
            toAmount: z.string(),
            toAmountMin: z.string(),
            approvalAddress: z.string(),
            feeCosts: z.array(FeeCost.zod).optional(),
            gasCosts: z.array(GasCost.zod).optional(),
            executionDuration: z.number(),
            tool: z.string(),
            data: EstimateData.zod.optional()
        });
    }
}

