/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

/**
* Fees included in the transfer
*/
export class FeeCost {
    /**
    * Name of the fee
    */
    'name': string;
    /**
    * Description of the fee costs
    */
    'description'?: string;
    /**
    * Percentage of how much fees are taken
    */
    'percentage': string;
    'token': Token;
    /**
    * The amount of fees
    */
    'amount'?: string;
    /**
    * The amount of fees in USD
    */
    'amountUSD': string;
    /**
    * Whether fee is included into transfer\'s `fromAmount`
    */
    'included': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUSD",
            "baseName": "amountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "boolean",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return FeeCost.attributeTypeMap;
    }

    public constructor() {
    }
}

