/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';
import { z } from 'zod';

/**
* Gas costs included in the transfer
*/
export class GasCost {
    /**
    * Can be one of `SUM`, `APPROVE` or `SEND`
    */
    'type': string;
    /**
    * Suggested current standard price for the chain
    */
    'price'?: string;
    /**
    * Estimation how much gas will be needed
    */
    'estimate'?: string;
    /**
    * Suggested gas limit
    */
    'limit'?: string;
    /**
    * Amount of the gas cost
    */
    'amount': string;
    /**
    * Amount of the gas cost in USD
    */
    'amountUSD'?: string;
    'token': Token;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "string",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUSD",
            "baseName": "amountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return GasCost.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod() {
        return z.object({
            type: z.string(),
            price: z.string().optional(),
            estimate: z.string().optional(),
            limit: z.string().optional(),
            amount: z.string(),
            amountUSD: z.string().optional(),
            token: Token.zod
        });
    }
}

