/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeeBalances } from './FeeBalances';
import { HttpFile } from '../http/http';

/**
* Integrator\'s fee balance by chain
*/
export class IntegratorResponse {
    /**
    * The integrator\'s name or wallet address
    */
    'integratorId': string;
    /**
    * The fee balances of the integrator
    */
    'feeBalances'?: Array<FeeBalances>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "integratorId",
            "baseName": "integratorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "feeBalances",
            "baseName": "feeBalances",
            "type": "Array<FeeBalances>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return IntegratorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

