/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LIFuelStatusStateEnum } from './LIFuelStatusStateEnum';
import { TxInfo } from './TxInfo';
import { HttpFile } from '../http/http';

export class LIFuelStatus {
    'status'?: LIFuelStatusStateEnum;
    'sending'?: TxInfo;
    'receiving'?: TxInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "LIFuelStatusStateEnum",
            "format": ""
        },
        {
            "name": "sending",
            "baseName": "sending",
            "type": "TxInfo",
            "format": ""
        },
        {
            "name": "receiving",
            "baseName": "receiving",
            "type": "TxInfo",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return LIFuelStatus.attributeTypeMap;
    }

    public constructor() {
    }
}



