/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowDenyPrefer } from './AllowDenyPrefer';
import { PossibilitiesTopicEnum } from './PossibilitiesTopicEnum';
import { HttpFile } from '../http/http';

/**
* Object defining preferences regarding chain, exchanges and bridges
*/
export class PossiblitiesRequest {
    /**
    * The ids of the chains that should be taken into consideration for the possibilities
    */
    'chains'?: Array<number>;
    'bridges'?: AllowDenyPrefer;
    'exchanges'?: AllowDenyPrefer;
    /**
    * To reduce the size of the returned possibilities, you can select which kind of information you like to see. Possible values are `chains`, `tokens`, `bridges`, and `exchanges`.
    */
    'include'?: Array<PossibilitiesTopicEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "chains",
            "baseName": "chains",
            "type": "Array<number>",
            "format": "number"
        },
        {
            "name": "bridges",
            "baseName": "bridges",
            "type": "AllowDenyPrefer",
            "format": ""
        },
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "AllowDenyPrefer",
            "format": ""
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<PossibilitiesTopicEnum>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return PossiblitiesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

