/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum QuoteBridgesEnum {
    Hop = 'hop',
    Multichain = 'multichain',
    Cbridge = 'cbridge',
    Celercircle = 'celercircle',
    Connext = 'connext',
    Hyphen = 'hyphen',
    Optimism = 'optimism',
    Polygon = 'polygon',
    Arbitrum = 'arbitrum',
    Avalanche = 'avalanche',
    Across = 'across',
    Stargate = 'stargate',
    Gnosis = 'gnosis',
    Omni = 'omni',
    Amarok = 'amarok',
    None = 'none',
    All = 'all',
    Lifuel = 'lifuel',
    Celerim = 'celerim',
    Default = 'default',
}
