/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Route } from './Route';
import { UnavailableRoutes } from './UnavailableRoutes';
import { HttpFile } from '../http/http';

/**
* A list of routes that can be used to realize the described transfer of tokens
*/
export class RoutesResponse {
    /**
    * List of possible `Routes` for the given transfer
    */
    'routes': Array<Route>;
    /**
    * An object representing the routes that are unavailable for the given transfer
    */
    'unavailableRoutes'?: Array<UnavailableRoutes>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "routes",
            "baseName": "routes",
            "type": "Array<Route>",
            "format": ""
        },
        {
            "name": "unavailableRoutes",
            "baseName": "unavailableRoutes",
            "type": "Array<UnavailableRoutes>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return RoutesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

