/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Step } from './Step';
import { Token } from './Token';
import { HttpFile } from '../http/http';

/**
* A route describing a transfer form a token to another
*/
export class Route {
    /**
    * Unique identifier of the route
    */
    'id': string;
    /**
    * The id of the sending chain
    */
    'fromChainId': number;
    /**
    * The amount that should be transferred in USD
    */
    'fromAmountUSD': string;
    /**
    * The amount that should be transferred
    */
    'fromAmount': string;
    'fromToken': Token;
    /**
    * The id of the receiving chain
    */
    'toChainId': number;
    /**
    * The estimated resulting amount of the `toToken` in USD as float with two decimals
    */
    'toAmountUSD': string;
    /**
    * The estimated resulting amount of the `toToken` including all decimals
    */
    'toAmount': string;
    /**
    * The minimal resultung amount of the `toToken` including all decimals
    */
    'toAmountMin': string;
    'toToken': Token;
    /**
    * Aggregation of th eunderlying gas costs in USD
    */
    'gasCostUSD'?: string;
    /**
    * The steps required to fulfill the transfer
    */
    'steps': Array<Step>;
    /**
    * The sending wallet address
    */
    'fromAddress'?: string;
    /**
    * The receiving wallet address
    */
    'toAddress'?: string;
    /**
    * Whether a chain switch is part of the route
    */
    'containsSwitchChain'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "fromAmountUSD",
            "baseName": "fromAmountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromToken",
            "baseName": "fromToken",
            "type": "Token",
            "format": ""
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "toAmountUSD",
            "baseName": "toAmountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "toAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmountMin",
            "baseName": "toAmountMin",
            "type": "string",
            "format": ""
        },
        {
            "name": "toToken",
            "baseName": "toToken",
            "type": "Token",
            "format": ""
        },
        {
            "name": "gasCostUSD",
            "baseName": "gasCostUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<Step>",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "containsSwitchChain",
            "baseName": "containsSwitchChain",
            "type": "boolean",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Route.attributeTypeMap;
    }

    public constructor() {
    }
}

