/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RouteOptions } from './RouteOptions';
import { HttpFile } from '../http/http';

/**
* A description of a token transfer
*/
export class RoutesRequest {
    /**
    * The sending chain id
    */
    'fromChainId': number;
    /**
    * The amount that should be transferred including all decimals (e.g. 1000000 for 1 USDC (6 decimals))
    */
    'fromAmount': string;
    /**
    * The address of the sending `Token`
    */
    'fromTokenAddress': string;
    /**
    * The id of the receiving chain
    */
    'toChainId': number;
    /**
    * The address of the receiving `Token`
    */
    'toTokenAddress': string;
    'options'?: RouteOptions;
    /**
    * The sending wallet address
    */
    'fromAddress'?: string;
    /**
    * The receicing wallet address
    */
    'toAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromTokenAddress",
            "baseName": "fromTokenAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "toTokenAddress",
            "baseName": "toTokenAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "RouteOptions",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return RoutesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

