/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowDenyPrefer } from './AllowDenyPrefer';
import { HttpFile } from '../http/http';

/**
* Optional settings for the route
*/
export class RouteOptions {
    /**
    * Custom string the developer who integrates LiFi can set
    */
    'integrator'?: string;
    /**
    * The maximum allowed slippage
    */
    'slippage'?: number;
    'bridges'?: AllowDenyPrefer;
    'exchanges'?: AllowDenyPrefer;
    /**
    * The way the resulting routes should be ordered
    */
    'order'?: RouteOptionsOrderEnum;
    /**
    * Whether chain switches should be allowed in the routes
    */
    'allowSwitchChain'?: boolean;
    /**
    * Integrators can set a wallet address as referrer to track them
    */
    'referrer'?: string;
    /**
    * The percent of the integrator\'s fee that is taken from every transaction
    */
    'fee'?: number;
    /**
    * The price impact threshold above which routes are hidden. As an example, one should specify 0.15 (15%) to hide routes with more than 15% price impact. The default is 10%.
    */
    'maxPriceImpact'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "integrator",
            "baseName": "integrator",
            "type": "string",
            "format": ""
        },
        {
            "name": "slippage",
            "baseName": "slippage",
            "type": "number",
            "format": "double"
        },
        {
            "name": "bridges",
            "baseName": "bridges",
            "type": "AllowDenyPrefer",
            "format": ""
        },
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "AllowDenyPrefer",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "RouteOptionsOrderEnum",
            "format": ""
        },
        {
            "name": "allowSwitchChain",
            "baseName": "allowSwitchChain",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "referrer",
            "baseName": "referrer",
            "type": "string",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number",
            "format": "double"
        },
        {
            "name": "maxPriceImpact",
            "baseName": "maxPriceImpact",
            "type": "number",
            "format": "double"
        }];

    static getAttributeTypeMap() {
        return RouteOptions.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RouteOptionsOrderEnum {
    Recommended = 'RECOMMENDED',
    Fastest = 'FASTEST',
    Cheapest = 'CHEAPEST',
    Safest = 'SAFEST'
}

