/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StepRequestExecutionProcessInner {
    'id'?: string;
    'startedAt'?: number;
    'message'?: string;
    'status'?: string;
    'txHash'?: string;
    'txLink'?: string;
    'doneAt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "number",
            "format": "number"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "txHash",
            "baseName": "txHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "txLink",
            "baseName": "txLink",
            "type": "string",
            "format": ""
        },
        {
            "name": "doneAt",
            "baseName": "doneAt",
            "type": "number",
            "format": "number"
        }    ];

    static getAttributeTypeMap() {
        return StepRequestExecutionProcessInner.attributeTypeMap;
    }

    public constructor() {
    }
}

