/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestActionFromToken } from './StepRequestActionFromToken';
import { HttpFile } from '../http/http';

export class StepRequestAction {
    'fromChainId'?: number;
    'toChainId'?: number;
    'fromToken'?: StepRequestActionFromToken;
    'toToken'?: StepRequestActionFromToken;
    'fromAmount'?: string;
    'fromAddress'?: string;
    'toAddress'?: string;
    'slippage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "fromToken",
            "baseName": "fromToken",
            "type": "StepRequestActionFromToken",
            "format": ""
        },
        {
            "name": "toToken",
            "baseName": "toToken",
            "type": "StepRequestActionFromToken",
            "format": ""
        },
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "fromAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "toAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "slippage",
            "baseName": "slippage",
            "type": "number",
            "format": "number"
        }];

    static getAttributeTypeMap() {
        return StepRequestAction.attributeTypeMap;
    }

    public constructor() {
    }
}

