/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestEstimateData } from './StepRequestEstimateData';
import { StepRequestEstimateFeeCostsInner } from './StepRequestEstimateFeeCostsInner';
import { StepRequestEstimateGasCostsInner } from './StepRequestEstimateGasCostsInner';
import { HttpFile } from '../http/http';

export class StepRequestEstimate {
    'fromAmount'?: string;
    'toAmount'?: string;
    'toAmountMin'?: string;
    'approvalAddress'?: string;
    'feeCosts'?: Array<StepRequestEstimateFeeCostsInner>;
    'gasCosts'?: Array<StepRequestEstimateGasCostsInner>;
    'data'?: StepRequestEstimateData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "toAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmountMin",
            "baseName": "toAmountMin",
            "type": "string",
            "format": ""
        },
        {
            "name": "approvalAddress",
            "baseName": "approvalAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "feeCosts",
            "baseName": "feeCosts",
            "type": "Array<StepRequestEstimateFeeCostsInner>",
            "format": ""
        },
        {
            "name": "gasCosts",
            "baseName": "gasCosts",
            "type": "Array<StepRequestEstimateGasCostsInner>",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "StepRequestEstimateData",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StepRequestEstimate.attributeTypeMap;
    }

    public constructor() {
    }
}

