/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';
import { z } from 'zod';

export class StepRequestEstimateDataBid {
    'user'?: string;
    'router'?: string;
    'initiator'?: string;
    'sendingChainId'?: number;
    'sendingAssetId'?: string;
    'amount'?: string;
    'receivingChainId'?: number;
    'receivingAssetId'?: string;
    'amountReceived'?: string;
    'receivingAddress'?: string;
    'transactionId'?: string;
    'expiry'?: number;
    'callDataHash'?: string;
    'callTo'?: string;
    'encryptedCallData'?: string;
    'sendingChainTxManagerAddress'?: string;
    'receivingChainTxManagerAddress'?: string;
    'bidExpiry'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "router",
            "baseName": "router",
            "type": "string",
            "format": ""
        },
        {
            "name": "initiator",
            "baseName": "initiator",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendingChainId",
            "baseName": "sendingChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "sendingAssetId",
            "baseName": "sendingAssetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "receivingChainId",
            "baseName": "receivingChainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "receivingAssetId",
            "baseName": "receivingAssetId",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountReceived",
            "baseName": "amountReceived",
            "type": "string",
            "format": ""
        },
        {
            "name": "receivingAddress",
            "baseName": "receivingAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiry",
            "baseName": "expiry",
            "type": "number",
            "format": "number"
        },
        {
            "name": "callDataHash",
            "baseName": "callDataHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "callTo",
            "baseName": "callTo",
            "type": "string",
            "format": ""
        },
        {
            "name": "encryptedCallData",
            "baseName": "encryptedCallData",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendingChainTxManagerAddress",
            "baseName": "sendingChainTxManagerAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "receivingChainTxManagerAddress",
            "baseName": "receivingChainTxManagerAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "bidExpiry",
            "baseName": "bidExpiry",
            "type": "number",
            "format": "number"
        }];

    static getAttributeTypeMap() {
        return StepRequestEstimateDataBid.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod() {
        return z.object({
            user: z.string().optional(),
            router: z.string().optional(),
            initiator: z.string().optional(),
            sendingChainId: z.number().optional(),
            sendingAssetId: z.string().optional(),
            amount: z.string().optional(),
            receivingChainId: z.number().optional(),
            receivingAssetId: z.string().optional(),
            amountReceived: z.string().optional(),
            receivingAddress: z.string().optional(),
            transactionId: z.string().optional(),
            expiry: z.number().optional(),
            callDataHash: z.string().optional(),
            callTo: z.string().optional(),
            encryptedCallData: z.string().optional(),
            sendingChainTxManagerAddress: z.string().optional(),
            receivingChainTxManagerAddress: z.string().optional(),
            bidExpiry: z.number().optional()
        });
    }
}

