/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestExecutionProcessInner } from './StepRequestExecutionProcessInner';
import { HttpFile } from '../http/http';

export class StepRequestExecution {
    'status'?: string;
    'process'?: Array<StepRequestExecutionProcessInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "process",
            "baseName": "process",
            "type": "Array<StepRequestExecutionProcessInner>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StepRequestExecution.attributeTypeMap;
    }

    public constructor() {
    }
}

