/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupportedChains {
    /**
    * Supported `from` chain
    */
    'fromChainId'?: string;
    /**
    * Supported `to` chain
    */
    'toChainId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromChainId",
            "baseName": "fromChainId",
            "type": "string",
            "format": ""
        },
        {
            "name": "toChainId",
            "baseName": "toChainId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupportedChains.attributeTypeMap;
    }

    public constructor() {
    }
}

