/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

export class TokenBalances {
    'token'?: Token;
    /**
    * Fee amount in tokens
    */
    'amount'?: string;
    /**
    * Fee amount in USD
    */
    'amountUsd'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUsd",
            "baseName": "amountUsd",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return TokenBalances.attributeTypeMap;
    }

    public constructor() {
    }
}

