/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Bridge } from './Bridge';
import { Exchange } from './Exchange';
import { HttpFile } from '../http/http';

export class Tools {
    'exchanges'?: Array<Exchange>;
    'bridges'?: Array<Bridge>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "Array<Exchange>",
            "format": ""
        },
        {
            "name": "bridges",
            "baseName": "bridges",
            "type": "Array<Bridge>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Tools.attributeTypeMap;
    }

    public constructor() {
    }
}

