/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

export class TxInfo {
    'txHash'?: string;
    'txLink'?: string;
    /**
    * The amount of token that will be / has been relayed
    */
    'amount'?: string;
    'token'?: Token;
    'chainId'?: number;
    'block'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "txHash",
            "baseName": "txHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "txLink",
            "baseName": "txLink",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        },
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "number",
            "format": ""
        },
        {
            "name": "block",
            "baseName": "block",
            "type": "number",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return TxInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

