/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusResponse } from './StatusResponse';
import { HttpFile } from '../http/http';

/**
* All transactions for a wallet address
*/
export class WalletAnalyticsResponse {
    /**
    * Wallet address
    */
    'walletAddress': string;
    'transactions': Array<StatusResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "walletAddress",
            "baseName": "walletAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<StatusResponse>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return WalletAnalyticsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

