/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Connection } from './Connection';
import { HttpFile } from '../http/http';

/**
* 
*/
export class ConnectionsResponse {
    /**
    * The possible connections
    */
    'connections'?: Array<Connection>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "connections",
            "baseName": "connections",
            "type": "Array<Connection>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return ConnectionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

