/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Object defining a single arbitrary contract call
*/
export class ContractCall {
    /**
    * The amount that will feed into this contract call. This is not dependent on how much was bridged or deposited before - it\'s the *expected* amount of token available on order to execute the call.
    */
    'fromAmount': string;
    /**
    * The token that will feed into this contract call. E.g. a ETH staking transaction would expect to have ETH available.
    */
    'fromTokenAddress': string;
    /**
    * The address of the contract to interact with.
    */
    'toContractAddress': string;
    /**
    * The calldata to be sent to the contract for the interaction on the destination chain.
    */
    'toContractCallData': string;
    /**
    * The estimated gas used by the destination call. If this value is incorrect, the interaction may fail -- choose this carefully!
    */
    'toContractGasLimit': string;
    /**
    * If the approval address is different thant the contract to call, specify that address here
    */
    'toApprovalAddress'?: string;
    /**
    * If the contract outputs a token, specify its address here. (E.g. staking ETH produces stETH)
    */
    'toTokenAddress'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromTokenAddress",
            "baseName": "fromTokenAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractAddress",
            "baseName": "toContractAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractCallData",
            "baseName": "toContractCallData",
            "type": "string",
            "format": ""
        },
        {
            "name": "toContractGasLimit",
            "baseName": "toContractGasLimit",
            "type": "string",
            "format": ""
        },
        {
            "name": "toApprovalAddress",
            "baseName": "toApprovalAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "toTokenAddress",
            "baseName": "toTokenAddress",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContractCall.attributeTypeMap;
    }

    public constructor() {
    }
}

