/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The defintion of an exchange with the avaiable chains
*/
export class ExchangeDefinition {
    /**
    * The exchange tool
    */
    'tool': ExchangeDefinitionToolEnum;
    /**
    * The available chains for this tool
    */
    'chains': Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tool",
            "baseName": "tool",
            "type": "ExchangeDefinitionToolEnum",
            "format": ""
        },
        {
            "name": "chains",
            "baseName": "chains",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExchangeDefinition.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ExchangeDefinitionToolEnum {
    _1inch = '1inch',
    Paraswap = 'paraswap',
    Openocean = 'openocean',
    _0x = '0x'
}

