/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GasPrice {
    'standard'?: number;
    'fast'?: number;
    'fastest'?: number;
    'lastUpdated'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "standard",
            "baseName": "standard",
            "type": "number",
            "format": ""
        },
        {
            "name": "fast",
            "baseName": "fast",
            "type": "number",
            "format": ""
        },
        {
            "name": "fastest",
            "baseName": "fastest",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GasPrice.attributeTypeMap;
    }

    public constructor() {
    }
}

