/**
 * Cross-chain Swap API
 * Cross-chain Swap provides the best cross-chain swap between different tokens.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';

/**
* Represents a single swap suggestion with details about the token, amount, and corresponding USD amount.
*/
export class GasSuggestionDetails {
    /**
    * Token details
    */
    'token': Token;
    /**
    * Amount in token's smallest unit (e.g. wei for ETH)
    */
    'amount': string;
    /**
    * Value of amount in USD
    */
    'amountUsd': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "Token",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUsd",
            "baseName": "amountUsd",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return GasSuggestionDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

/**
* Contains details about the swap suggestion.
*/
export class GasSuggestionResponse {
    /**
    * Indicates whether or not the swap is available.
    */
    'available': boolean;
    /**
    * Contains recommended swap details
    */
    'recommended'?: GasSuggestionDetails;
    /**
    * Contains upper limit swap details
    */
    'limit'?: GasSuggestionDetails;
    /**
    * Contains service fee details
    */
    'serviceFee'?: GasSuggestionDetails;
    /**
    * Details of the token to be swapped from
    */
    'fromToken'?: Token;
    /**
    * The amount to be swapped from the token in its smallest unit
    */
    'fromAmount'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "available",
            "baseName": "available",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "recommended",
            "baseName": "recommended",
            "type": "SwapSuggestionDetails",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "SwapSuggestionDetails",
            "format": ""
        },
        {
            "name": "serviceFee",
            "baseName": "serviceFee",
            "type": "SwapSuggestionDetails",
            "format": ""
        },
        {
            "name": "fromToken",
            "baseName": "fromToken",
            "type": "Token",
            "format": ""
        },
        {
            "name": "fromAmount",
            "baseName": "fromAmount",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return GasSuggestionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
