/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The transaction request
*/
export class IntegratorWithdrawalResponseTransactionRequest {
    /**
    * The transaction\'s data
    */
    'data'?: string;
    /**
    * The FeeCollector\'s contract address for the specified chain
    */
    'to'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IntegratorWithdrawalResponseTransactionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

