/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IntegratorWithdrawalResponseTransactionRequest } from './IntegratorWithdrawalResponseTransactionRequest';
import { HttpFile } from '../http/http';

/**
* Transaction request for withdrawing integrator\'s collected fees for the specified chain
*/
export class IntegratorWithdrawalResponse {
    'transactionRequest': IntegratorWithdrawalResponseTransactionRequest;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "transactionRequest",
            "baseName": "transactionRequest",
            "type": "IntegratorWithdrawalResponseTransactionRequest",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return IntegratorWithdrawalResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

