/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BridgeDefinition } from './BridgeDefinition';
import { Chain } from './Chain';
import { ExchangeDefinition } from './ExchangeDefinition';
import { Token } from './Token';
import { HttpFile } from '../http/http';

/**
* Object listing current possibilities for any-to-any cross-chain-swaps based on the provided preferences
*/
export class PossibilitiesResponse {
    /**
    * Possible chains that can be sent from or to
    */
    'chains': Array<Chain>;
    /**
    * Possible `Tokens` that can be transferred
    */
    'tokens': Array<Token>;
    /**
    * Possible exchanges that can be used for transfers
    */
    'exchanges': Array<ExchangeDefinition>;
    /**
    * Possible bridges that can be used for transfers
    */
    'bridges': Array<BridgeDefinition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "chains",
            "baseName": "chains",
            "type": "Array<Chain>",
            "format": ""
        },
        {
            "name": "tokens",
            "baseName": "tokens",
            "type": "Array<Token>",
            "format": ""
        },
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "Array<ExchangeDefinition>",
            "format": ""
        },
        {
            "name": "bridges",
            "baseName": "bridges",
            "type": "Array<BridgeDefinition>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return PossibilitiesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

