/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnavailableRoutes } from './UnavailableRoutes';
import { HttpFile } from '../http/http';

export class QuoteGet404Response {
    /**
    * The error message
    */
    'message'?: string;
    'errors'?: Array<UnavailableRoutes>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<UnavailableRoutes>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return QuoteGet404Response.attributeTypeMap;
    }

    public constructor() {
    }
}

