/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum QuoteExchangesEnum {
    _1inch = '1inch',
    Paraswap = 'paraswap',
    Openocean = 'openocean',
    _0x = '0x',
    Dodo = 'dodo',
    Uniswap = 'uniswap',
    Sushiswap = 'sushiswap',
    Quickswap = 'quickswap',
    Honeyswap = 'honeyswap',
    Pancakeswap = 'pancakeswap',
    Spookyswap = 'spookyswap',
    Viperswap = 'viperswap',
    Solarbeam = 'solarbeam',
    Spiritswap = 'spiritswap',
    None = 'none',
    All = 'all',
    Default = 'default',
}
