/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionInfo } from './TransactionInfo';
import { HttpFile } from '../http/http';

/**
* The current status of a transfer
*/
export class StatusResponse {
    'sending': TransactionInfo;
    'receiving'?: TransactionInfo;
    /**
    * The current status of the transfer. Can be `PENDING`, `DONE`, `NOT_FOUND` or `FAILED`
    */
    'status': StatusResponseStatusEnum;
    /**
    * A more specific substatus. This is available for PENDING and DONE statuses. More information can be found here: https://docs.li.fi/more-integration-options/li.fi-api/checking-the-status-of-a-transaction
    */
    'substatus'?: StatusResponseSubstatusEnum;
    /**
    * The tool used for this transfer
    */
    'tool': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "sending",
            "baseName": "sending",
            "type": "TransactionInfo",
            "format": ""
        },
        {
            "name": "receiving",
            "baseName": "receiving",
            "type": "TransactionInfo",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StatusResponseStatusEnum",
            "format": ""
        },
        {
            "name": "substatus",
            "baseName": "substatus",
            "type": "StatusResponseSubstatusEnum",
            "format": ""
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum StatusResponseStatusEnum {
    NotFound = 'NOT_FOUND',
    Invalid = 'INVALID',
    Pending = 'PENDING',
    Done = 'DONE',
    Failed = 'FAILED'
}
export enum StatusResponseSubstatusEnum {
    WaitSourceConfirmations = 'WAIT_SOURCE_CONFIRMATIONS',
    WaitDestinationTransaction = 'WAIT_DESTINATION_TRANSACTION',
    BridgeNotAvailable = 'BRIDGE_NOT_AVAILABLE',
    ChainNotAvailable = 'CHAIN_NOT_AVAILABLE',
    NotProcessableRefundNeeded = 'NOT_PROCESSABLE_REFUND_NEEDED',
    RefundInProgress = 'REFUND_IN_PROGRESS',
    UnknownError = 'UNKNOWN_ERROR',
    Completed = 'COMPLETED',
    Partial = 'PARTIAL',
    Refunded = 'REFUNDED'
}

