/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from './Action';
import { Estimate } from './Estimate';
import { HttpFile } from '../http/http';
import { z } from 'zod';
import { ToolDetails } from './ToolDetails';

/**
* Object that represents one step of a `Route`
*/
export class Step {
    /**
    * Unique identifier of the step
    */
    'id': string;
    /**
    * The type of the step
    */
    'type': StepTypeEnum;
    /**
    * The tool used for this step. E.g. `connext`
    */
    'tool': string;
    'action': Action;
    'estimate'?: Estimate;
    /**
    * A string containing tracking information about the integrator of the API
    */
    'integrator'?: string;
    /**
    * A string containing tracking information about the referrer of the integrator
    */
    'referrer'?: string;
    /**
    * An objection containing status information about the execution
    */
    'execution'?: any | null;
    /**
    * An ether.js TransactionRequest that can be triggered using a wallet provider. (https://docs.ethers.io/v5/api/providers/types/#providers-TransactionRequest)
    */
    'transactionRequest'?: any | null;

    'includedSteps'?: Array<Step>;

    'toolDetails': ToolDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "StepTypeEnum",
            "format": ""
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "Action",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "Estimate",
            "format": ""
        },
        {
            "name": "integrator",
            "baseName": "integrator",
            "type": "string",
            "format": ""
        },
        {
            "name": "referrer",
            "baseName": "referrer",
            "type": "string",
            "format": ""
        },
        {
            "name": "execution",
            "baseName": "execution",
            "type": "any",
            "format": ""
        },
        {
            "name": "transactionRequest",
            "baseName": "transactionRequest",
            "type": "any",
            "format": ""
        },
        {
            "name": "includedSteps",
            "baseName": "includedSteps",
            "type": "Array<Step>",
            "format": ""
        },
        {
            "name": "toolDetails",
            "baseName": "toolDetails",
            "type": "ToolDetails",
            "format": ""
        }
    ];

    static getAttributeTypeMap() {
        return Step.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod(): z.ZodType<Step> {
        return z.object({
            id: z.string(),
            type: StepTypeEnum.zod(),
            tool: z.string(),
            action: Action.zod,
            estimate: Estimate.zod.optional(),
            integrator: z.string().optional(),
            referrer: z.string().optional(),
            execution: z.unknown().nullable().optional(),
            transactionRequest: z.unknown().nullable().optional(),
            includedSteps: z.lazy(() => z.array(Step.zod).optional()),
            toolDetails: ToolDetails.zod
        });
    }
}


export enum StepTypeEnum {
    Swap = 'swap',
    Cross = 'cross',
    Lifi = 'lifi'
}

export namespace StepTypeEnum {
    export function zod(): z.ZodSchema<StepTypeEnum> {
        return z.enum([
            StepTypeEnum.Swap,
            StepTypeEnum.Cross,
            StepTypeEnum.Lifi
        ]).or(z.string()) as z.ZodSchema<StepTypeEnum> // Just in case the server returns an unknown value
    }
}
