/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestEstimateGasCostsInnerToken } from './StepRequestEstimateGasCostsInnerToken';
import { HttpFile } from '../http/http';

export class StepRequestEstimateGasCostsInner {
    'type'?: string;
    'price'?: string;
    'estimate'?: string;
    'limit'?: string;
    'amount'?: string;
    'amountUSD'?: string;
    'token'?: StepRequestEstimateGasCostsInnerToken;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "string",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUSD",
            "baseName": "amountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "StepRequestEstimateGasCostsInnerToken",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StepRequestEstimateGasCostsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

