/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestActionFromToken } from './StepRequestActionFromToken';
import { HttpFile } from '../http/http';

export class StepRequestEstimateFeeCostsInner {
    'name'?: string;
    'description'?: string;
    'percentage'?: string;
    'token'?: StepRequestActionFromToken;
    'amount'?: string;
    'amountUSD'?: string;
    'included'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "string",
            "format": ""
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "StepRequestActionFromToken",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "amountUSD",
            "baseName": "amountUSD",
            "type": "string",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "boolean",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StepRequestEstimateFeeCostsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

