/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StepRequestAction } from './StepRequestAction';
import { StepRequestEstimate } from './StepRequestEstimate';
import { StepRequestExecution } from './StepRequestExecution';
import { HttpFile } from '../http/http';

/**
* A step object
*/
export class StepRequest {
    'id'?: string;
    'type'?: string;
    'tool'?: string;
    'action'?: StepRequestAction;
    'estimate'?: StepRequestEstimate;
    'integrator'?: string;
    'execution'?: StepRequestExecution;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "StepRequestAction",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "StepRequestEstimate",
            "format": ""
        },
        {
            "name": "integrator",
            "baseName": "integrator",
            "type": "string",
            "format": ""
        },
        {
            "name": "execution",
            "baseName": "execution",
            "type": "StepRequestExecution",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return StepRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

