/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';
import { z } from 'zod';

/**
* Representation of a Token
*/
export class Token {
    /**
    * Address of the token
    */
    'address': string;
    /**
    * Number of decimals the token uses
    */
    'decimals': number;
    /**
    * Symbol of the token
    */
    'symbol': string;
    /**
    * Id of the token\'s chain
    */
    'chainId': number;
    /**
    * Identifier for the token
    */
    'coinKey'?: string;
    /**
    * Name of the token
    */
    'name': string;
    /**
    * Logo of the token
    */
    'logoURI'?: string;
    /**
    * Token price in USD
    */
    'priceUSD'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number",
            "format": "number"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "number",
            "format": "number"
        },
        {
            "name": "coinKey",
            "baseName": "coinKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoURI",
            "baseName": "logoURI",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceUSD",
            "baseName": "priceUSD",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Token.attributeTypeMap;
    }

    public constructor() {
    }

    static get zod() {
        return z.object({
            address: z.string(),
            decimals: z.number(),
            symbol: z.string(),
            chainId: z.number(),
            coinKey: z.string().optional(),
            name: z.string(),
            logoURI: z.string().optional(),
            priceUSD: z.string().optional()
        });
    }
}

