/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Token } from './Token';
import { HttpFile } from '../http/http';

export class TokensGet200Response {
    /**
    * The requested tokens
    */
    'tokens'?: Array<Token>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "tokens",
            "baseName": "tokens.[0]",
            "type": "Array<Token>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return TokensGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

