/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Action } from './Action';
import { HttpFile } from '../http/http';

/**
* Describes why a certain operation (like a quote request) failed.
*/
export class ToolError {
    /**
    * The type of error that occurred.
    */
    'errorType'?: ToolErrorErrorTypeEnum;
    /**
    * The error code.
    */
    'code'?: ToolErrorCodeEnum;
    'action'?: Action;
    /**
    * The tool that emitted the error.
    */
    'tool'?: string;
    /**
    * A human-readable message describing the error.
    */
    'message'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "errorType",
            "baseName": "errorType",
            "type": "ToolErrorErrorTypeEnum",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "ToolErrorCodeEnum",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "Action",
            "format": ""
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return ToolError.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ToolErrorErrorTypeEnum {
    NoQuote = 'NO_QUOTE'
}
export enum ToolErrorCodeEnum {
    NoPossibleRoute = 'NO_POSSIBLE_ROUTE',
    InsufficientLiquidity = 'INSUFFICIENT_LIQUIDITY',
    ToolTimeout = 'TOOL_TIMEOUT',
    UnknownError = 'UNKNOWN_ERROR',
    RpcError = 'RPC_ERROR',
    AmountTooLow = 'AMOUNT_TOO_LOW',
    AmountTooHigh = 'AMOUNT_TOO_HIGH',
    FeesHigherThanAmount = 'FEES_HIGHER_THAN_AMOUNT',
    DifferentRecipientNotSupported = 'DIFFERENT_RECIPIENT_NOT_SUPPORTED',
    ToolSpecificError = 'TOOL_SPECIFIC_ERROR',
    CannotGuaranteeMinAmount = 'CANNOT_GUARANTEE_MIN_AMOUNT',
    RateLimitExceeded = 'RATE_LIMIT_EXCEEDED'
}

