/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ToolError } from './ToolError';
import { HttpFile } from '../http/http';

export class UnavailableRoutesFailedInner {
    /**
    * The complete representation of the attempted route.
    */
    'overallPath'?: string;
    /**
    * An object with all subpaths that generated one or more errors
    */
    'subpaths'?: { [key: string]: ToolError; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "overallPath",
            "baseName": "overallPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "subpaths",
            "baseName": "subpaths",
            "type": "{ [key: string]: ToolError; }",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return UnavailableRoutesFailedInner.attributeTypeMap;
    }

    public constructor() {
    }
}

