/**
 * LI.FI API
 * LI.FI provides the best cross-chain swap across all liquidity pools and bridges.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UnavailableRoutesFailedInner } from './UnavailableRoutesFailedInner';
import { UnavailableRoutesFilteredOutInner } from './UnavailableRoutesFilteredOutInner';
import { HttpFile } from '../http/http';

export class UnavailableRoutes {
    /**
    * An object containing information about routes that were intentionally filtered out.
    */
    'filteredOut'?: Array<UnavailableRoutesFilteredOutInner>;
    /**
    * An object containing information about failed routes.
    */
    'failed'?: Array<UnavailableRoutesFailedInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "filteredOut",
            "baseName": "filteredOut",
            "type": "Array<UnavailableRoutesFilteredOutInner>",
            "format": ""
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "Array<UnavailableRoutesFailedInner>",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return UnavailableRoutes.attributeTypeMap;
    }

    public constructor() {
    }
}

